<?php
/**
 * Internationalisation (i18n) — FR par défaut, + EN et ES.
 * La langue est mémorisée en session et se change via ?lang=xx.
 * Pour ajouter une langue : l'ajouter à $dispo et compléter $TRAD.
 */
$dispo = ['fr', 'en', 'es'];
if (isset($_GET['lang']) && in_array($_GET['lang'], $dispo, true)) {
    $_SESSION['lang'] = $_GET['lang'];
}
$GLOBALS['LANG'] = (isset($_SESSION['lang']) && in_array($_SESSION['lang'], $dispo, true)) ? $_SESSION['lang'] : 'fr';

$GLOBALS['TRAD'] = [
 'fr' => [
  'nav_accueil'=>"ACCUEIL", 'nav_concept'=>"CONCEPT", 'nav_salles'=>"LES SALLES",
  'nav_infos'=>"INFOS PRATIQUES", 'nav_regles'=>"RÈGLES", 'nav_contact'=>"CONTACT", 'nav_classement'=>"Classement",
  'btn_reserver'=>"RÉSERVER", 'btn_espace'=>"MON ESPACE", 'btn_connexion'=>"Connexion",
  'foot_tagline'=>"Escape game nocturne immersif.",
  'foot_quote'=>"«&nbsp;Vous n'auriez jamais dû trouver cet endroit.&nbsp;»",
  'foot_h_nav'=>"Navigation", 'foot_h_infos'=>"Infos pratiques", 'foot_h_pret'=>"Prêt·e&nbsp;?",
  'foot_resa_txt'=>"Réservez votre nuit dans les Backrooms.", 'foot_contact'=>"Nous contacter",
  'foot_jours'=>"Vendredi soir, samedi soir, jours fériés et vacances scolaires (sauf le lundi)",
  'foot_rights'=>"Tous droits réservés.", 'foot_by'=>"Réalisé par",
  'home_intro'=>"Inspiré de la légende urbaine des Backrooms, une dimension parallèle angoissante accessible uniquement par un « bug de la réalité », notre concept exploite la psychologie des espaces liminaux : des lieux de transition vides, répétitifs et vaguement familiers, qui génèrent un sentiment d'isolement et d'étrangeté. L'expérience se déroule du soir (19h-20h) au lendemain matin, avec 4 heures de jeu effectif pour tenter de « sortir des Backrooms ». Les décors immersifs et nos comédiens rendent cette expérience inoubliable !",
  'home_btn_reserver'=>"RÉSERVER UNE SESSION", 'home_btn_plus'=>"EN SAVOIR PLUS &gt;",
  'feat_entrer'=>"ENTRER DANS<br>LES BACKROOMS &gt;", 'feat_joueurs'=>"JOUEURS &gt;", 'feat_regles'=>"RÈGLES &gt;",
  'video_titre'=>"LA BANDE-ANNONCE", 'video_sous'=>"Plongez dans l'ambiance avant de franchir la porte.",
 ],
 'en' => [
  'nav_accueil'=>"HOME", 'nav_concept'=>"CONCEPT", 'nav_salles'=>"THE ROOMS",
  'nav_infos'=>"VISITOR INFO", 'nav_regles'=>"RULES", 'nav_contact'=>"CONTACT", 'nav_classement'=>"Leaderboard",
  'btn_reserver'=>"BOOK NOW", 'btn_espace'=>"MY ACCOUNT", 'btn_connexion'=>"Log in",
  'foot_tagline'=>"Immersive nighttime escape game.",
  'foot_quote'=>"«&nbsp;You should never have found this place.&nbsp;»",
  'foot_h_nav'=>"Navigation", 'foot_h_infos'=>"Visitor info", 'foot_h_pret'=>"Ready?",
  'foot_resa_txt'=>"Book your night in the Backrooms.", 'foot_contact'=>"Contact us",
  'foot_jours'=>"Friday & Saturday evenings, public holidays and school holidays (except Mondays)",
  'foot_rights'=>"All rights reserved.", 'foot_by'=>"Made by",
  'home_intro'=>"Inspired by the urban legend of the Backrooms — an unsettling parallel dimension reachable only through a « glitch in reality » — our concept plays on the psychology of liminal spaces: empty, repetitive, vaguely familiar in-between places that create a feeling of isolation and unease. The experience runs from the evening (7–8 pm) until the next morning, with 4 hours of actual gameplay to try to « escape the Backrooms ». Immersive sets and our live actors make it unforgettable!",
  'home_btn_reserver'=>"BOOK A SESSION", 'home_btn_plus'=>"LEARN MORE &gt;",
  'feat_entrer'=>"ENTER THE<br>BACKROOMS &gt;", 'feat_joueurs'=>"PLAYERS &gt;", 'feat_regles'=>"RULES &gt;",
  'video_titre'=>"THE TRAILER", 'video_sous'=>"Get a taste of the atmosphere before you step through the door.",
 ],
 'es' => [
  'nav_accueil'=>"INICIO", 'nav_concept'=>"CONCEPTO", 'nav_salles'=>"LAS SALAS",
  'nav_infos'=>"INFO PRÁCTICA", 'nav_regles'=>"REGLAS", 'nav_contact'=>"CONTACTO", 'nav_classement'=>"Clasificación",
  'btn_reserver'=>"RESERVAR", 'btn_espace'=>"MI ESPACIO", 'btn_connexion'=>"Iniciar sesión",
  'foot_tagline'=>"Escape game nocturno inmersivo.",
  'foot_quote'=>"«&nbsp;Nunca deberías haber encontrado este lugar.&nbsp;»",
  'foot_h_nav'=>"Navegación", 'foot_h_infos'=>"Info práctica", 'foot_h_pret'=>"¿Listo?",
  'foot_resa_txt'=>"Reserva tu noche en las Backrooms.", 'foot_contact'=>"Contáctanos",
  'foot_jours'=>"Viernes y sábados por la noche, festivos y vacaciones escolares (excepto lunes)",
  'foot_rights'=>"Todos los derechos reservados.", 'foot_by'=>"Hecho por",
  'home_intro'=>"Inspirado en la leyenda urbana de las Backrooms — una inquietante dimensión paralela a la que solo se accede por un « fallo de la realidad » — nuestro concepto juega con la psicología de los espacios liminales: lugares de paso vacíos, repetitivos y vagamente familiares que provocan una sensación de aislamiento y extrañeza. La experiencia transcurre desde la tarde (19-20 h) hasta la mañana siguiente, con 4 horas de juego efectivo para intentar « salir de las Backrooms ». ¡Los decorados inmersivos y nuestros actores la hacen inolvidable!",
  'home_btn_reserver'=>"RESERVAR UNA SESIÓN", 'home_btn_plus'=>"SABER MÁS &gt;",
  'feat_entrer'=>"ENTRAR EN<br>LAS BACKROOMS &gt;", 'feat_joueurs'=>"JUGADORES &gt;", 'feat_regles'=>"REGLAS &gt;",
  'video_titre'=>"EL TRÁILER", 'video_sous'=>"Sumérgete en el ambiente antes de cruzar la puerta.",
 ],
];

function t($k) {
    $l = $GLOBALS['LANG'];
    return $GLOBALS['TRAD'][$l][$k] ?? ($GLOBALS['TRAD']['fr'][$k] ?? $k);
}
// --- Page « Les salles » ---
$__salles = [
 'fr' => [
  'sl_sub'=>"Trois niveaux de difficulté, une seule promesse : vous faire perdre la notion du temps.",
  's1_tag'=>"FACILE", 's1_nom'=>"Le Niveau 0",
  's1_desc'=>"Exploration et cartographie, sans aucune menace. Décors jaunes, moquette humide, néons qui bourdonnent et une salle « supermarché ». Idéale en famille.",
  's1_a'=>"4 h de jeu + repas et nuit sur place", 's1_b'=>"2 à 10 joueurs", 's1_c'=>"Dès 10 ans", 's1_d'=>"Aucun comédien — ambiance contemplative", 's1_prix'=>"À partir de 145 €/pers",
  's2_tag'=>"STANDARD", 's2_nom'=>"Les Couloirs jaunes",
  's2_desc'=>"Entrepôt sombre, tuyauteries et coupures de courant : gestion du stress et recherche de ressources, avec l'intervention de comédiens (les entités).",
  's2_a'=>"4 h de jeu + repas et nuit sur place", 's2_b'=>"2 à 10 joueurs", 's2_c'=>"Dès 14 ans", 's2_d'=>"Présence de comédiens — montée d'adrénaline", 's2_prix'=>"À partir de 145 €/pers",
  's3_tag'=>"HARDCORE", 's3_nom'=>"Le Niveau !",
  's3_desc'=>"Noir complet, signaux d'alarme, stimuli sonores agressifs et traque ininterrompue par les entités. Pour les plus téméraires — le mot « LUMIÈRE » sera tentant…",
  's3_a'=>"5 h de jeu + repas et nuit sur place", 's3_b'=>"2 à 10 joueurs", 's3_c'=>"Dès 16 ans", 's3_d'=>"Horreur extrême — traque continue", 's3_prix'=>"À partir de 155 €/pers",
  'sl_note'=>"Tarif dégressif selon l'effectif — hébergement et repas inclus.",
 ],
 'en' => [
  'sl_sub'=>"Three difficulty levels, one promise: to make you lose all track of time.",
  's1_tag'=>"EASY", 's1_nom'=>"Level 0",
  's1_desc'=>"Exploration and mapping, with no threat at all. Yellow walls, damp carpet, buzzing fluorescent lights and a « supermarket » room. Perfect for families.",
  's1_a'=>"4 hrs of play + meal and overnight stay", 's1_b'=>"2 to 10 players", 's1_c'=>"Ages 10+", 's1_d'=>"No actors — contemplative mood", 's1_prix'=>"From €145/person",
  's2_tag'=>"STANDARD", 's2_nom'=>"The Yellow Corridors",
  's2_desc'=>"Dark warehouse, pipework and power cuts: stress management and resource hunting, with live actors (the entities) stepping in.",
  's2_a'=>"4 hrs of play + meal and overnight stay", 's2_b'=>"2 to 10 players", 's2_c'=>"Ages 14+", 's2_d'=>"Live actors — rising adrenaline", 's2_prix'=>"From €145/person",
  's3_tag'=>"HARDCORE", 's3_nom'=>"Level !",
  's3_desc'=>"Total darkness, alarm signals, aggressive sound stimuli and relentless pursuit by the entities. For the boldest — the word « LIGHT » will be tempting…",
  's3_a'=>"5 hrs of play + meal and overnight stay", 's3_b'=>"2 to 10 players", 's3_c'=>"Ages 16+", 's3_d'=>"Extreme horror — continuous chase", 's3_prix'=>"From €155/person",
  'sl_note'=>"Decreasing rate by group size — accommodation and meals included.",
 ],
 'es' => [
  'sl_sub'=>"Tres niveles de dificultad, una sola promesa: hacerte perder la noción del tiempo.",
  's1_tag'=>"FÁCIL", 's1_nom'=>"El Nivel 0",
  's1_desc'=>"Exploración y cartografía, sin ninguna amenaza. Paredes amarillas, moqueta húmeda, fluorescentes que zumban y una sala « supermercado ». Ideal en familia.",
  's1_a'=>"4 h de juego + comida y noche en el lugar", 's1_b'=>"2 a 10 jugadores", 's1_c'=>"Desde 10 años", 's1_d'=>"Sin actores — ambiente contemplativo", 's1_prix'=>"Desde 145 €/persona",
  's2_tag'=>"ESTÁNDAR", 's2_nom'=>"Los Pasillos Amarillos",
  's2_desc'=>"Almacén oscuro, tuberías y cortes de luz: gestión del estrés y búsqueda de recursos, con la intervención de actores (las entidades).",
  's2_a'=>"4 h de juego + comida y noche en el lugar", 's2_b'=>"2 a 10 jugadores", 's2_c'=>"Desde 14 años", 's2_d'=>"Presencia de actores — sube la adrenalina", 's2_prix'=>"Desde 145 €/persona",
  's3_tag'=>"EXTREMO", 's3_nom'=>"¡El Nivel !",
  's3_desc'=>"Oscuridad total, señales de alarma, estímulos sonoros agresivos y persecución incesante de las entidades. Para los más atrevidos — la palabra « LUZ » será tentadora…",
  's3_a'=>"5 h de juego + comida y noche en el lugar", 's3_b'=>"2 a 10 jugadores", 's3_c'=>"Desde 16 años", 's3_d'=>"Horror extremo — persecución continua", 's3_prix'=>"Desde 155 €/persona",
  'sl_note'=>"Tarifa decreciente según el grupo — alojamiento y comidas incluidos.",
 ],
];
foreach ($__salles as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Pages Concept / Règles / Contact ---
$__pages = [
 'fr' => [
  'cp_sub'=>"Le principe de l'escape game de nuit",
  'cp_lead'=>"Vous et votre équipe vous réveillez dans les <strong>Backrooms</strong>, un labyrinthe infini de pièces décrépites où la réalité semble se déliter.<br><span class='lead-objectif'>Votre objectif :</span> explorer, résoudre des énigmes et trouver le moyen de vous échapper… avant qu'il ne soit trop tard.",
  'cp_p1t'=>"EXPLORER", 'cp_p1d'=>"Parcourez des salles immersives et flippantes ; chaque détail peut être un indice.",
  'cp_p2t'=>"RÉSOUDRE", 'cp_p2d'=>"Affrontez des défis de logique, observez l'environnement et collaborez pour progresser.",
  'cp_p3t'=>"SURVIVRE", 'cp_p3d'=>"Quelque chose rôde dans les Backrooms… restez vigilants et ne faites pas de bruit inutile.",
  'cp_p4t'=>"S'ÉCHAPPER", 'cp_p4d'=>"Trouvez la sortie avant la fin du temps et inscrivez votre exploit dans le monde réel.",
  'cp_s2t'=>"CE QUI VOUS ATTEND", 'cp_s2sub'=>"On va faire quoi pendant l'escape game ?",
  'cp_m1t'=>"Immersion totale", 'cp_m1d'=>"Des décors réalistes et une ambiance sonore oppressante pour une expérience inoubliable.",
  'cp_m2t'=>"Épreuves collaboratives", 'cp_m2d'=>"Observation, logique et communication seront essentielles pour avancer ensemble.",
  'cp_m3t'=>"Frisson garanti", 'cp_m3d'=>"Des rencontres inattendues avec des « entités » qui mettront vos nerfs à rude épreuve.",
  'cp_m4t'=>"Exploration libre", 'cp_m4d'=>"Fouillez chaque recoin : le moindre détail peut cacher un indice crucial.",
  'cp_m5t'=>"Course contre le temps", 'cp_m5d'=>"4 à 5 heures pour vous échapper… le chrono joue contre vous, à chaque seconde.",
  'cp_s3t'=>"STATISTIQUES", 'cp_s3sub'=>"Est-ce que l'escape game est facile ?",
  'cp_st1'=>"Temps maximum pour s'échapper", 'cp_st2'=>"Joueurs par équipe", 'cp_st3'=>"Salles à explorer", 'cp_st4'=>"Taux de réussite", 'cp_st5'=>"Adrénaline garantie",
  'cp_classlink'=>"VOIR LE CLASSEMENT DES ÉQUIPES &gt;",
  'cp_s4t'=>"LES RÈGLES", 'cp_s4sub'=>"Quelles sont les règles ?", 'cp_rtitle'=>"Les règles de survie",
  'cp_r1'=>"Ne vous séparez jamais de votre équipe.", 'cp_r2'=>"Si vous entendez quelque chose d'inhabituel, restez silencieux.", 'cp_r3'=>"Chaque détail de votre environnement peut être un indice.", 'cp_r4'=>"Le temps joue contre vous, restez concentrés.", 'cp_r5'=>"Certaines parties ne devraient pas être ouvertes.",
  'cp_allrules'=>"VOIR TOUTES LES RÈGLES &gt;", 'cp_avist'=>"ILS ONT SURVÉCU", 'cp_avissub'=>"… et ils témoignent",
  'rg_title'=>"RÈGLES DU JEU", 'rg_sub'=>"Pour que l'expérience reste intense et sûre pour tout le monde.",
  'rg_alerte'=>"Le mot d'arrêt <strong>« LUMIÈRE »</strong> met instantanément fin à la partie, à tout moment et sans justification.",
  'rg_c1t'=>"Avant la partie", 'rg_c1a'=>"Présentez-vous <strong>30 minutes avant</strong> l'horaire de votre session.", 'rg_c1b'=>"Âge minimum selon la salle : <strong>10 ans</strong> (Salle 1), <strong>14 ans</strong> (Salle 2), <strong>16 ans</strong> (Salle 3).", 'rg_c1c'=>"Équipes de <strong>2 à 10 joueurs</strong>.", 'rg_c1d'=>"Casier fourni pour vos effets : téléphones et montres connectées y restent.",
  'rg_c2t'=>"Pendant l'immersion", 'rg_c2a'=>"Aucune photo ni vidéo (pour préserver le mystère et les énigmes).", 'rg_c2b'=>"Restez en groupe : se séparer fait perdre un temps précieux.", 'rg_c2c'=>"Manipulez les décors avec soin, ne forcez jamais un mécanisme.", 'rg_c2d'=>"Un <strong>indice</strong> peut être demandé à tout moment via le talkie fourni.",
  'rg_c3t'=>"Sécurité", 'rg_c3a'=>"Le mot d'arrêt « <strong>LUMIÈRE</strong> » met instantanément fin à la partie.", 'rg_c3b'=>"Sorties de secours signalées et accessibles en permanence.", 'rg_c3c'=>"Un comédien-maître du jeu vous surveille discrètement tout du long.", 'rg_c3d'=>"Interdit aux personnes sous l'emprise d'alcool ou de stupéfiants.",
  'rg_c4t'=>"Le score", 'rg_c4a'=>"L'objectif : <strong>« sortir des Backrooms »</strong> avant la fin du temps imparti.", 'rg_c4b'=>"Des points bonus récompensent les énigmes résolues sans indice.", 'rg_c4c'=>"Votre temps de sortie et votre score apparaissent dans votre espace privé.", 'rg_c4d'=>"Les meilleures équipes rejoignent le classement public.",
  'rg_cta'=>"Prêt·e à tenter l'expérience ?",
  'ct_title'=>"NOUS CONTACTER", 'ct_sub'=>"Une question sur l'expérience ? Écrivez-nous, on vous répond rapidement.",
  'ct_nom'=>"Votre nom *", 'ct_email'=>"Votre email *", 'ct_sujet'=>"Sujet *", 'ct_msg'=>"Message *", 'ct_send'=>"Envoyer le message",
  'ct_iadr'=>"Adresse", 'ct_itel'=>"Téléphone", 'ct_ihor'=>"Horaires", 'ct_ires'=>"Réseaux sociaux",
 ],
 'en' => [
  'cp_sub'=>"How the nighttime escape game works",
  'cp_lead'=>"You and your team wake up in the <strong>Backrooms</strong>, an endless maze of decaying rooms where reality seems to fall apart.<br><span class='lead-objectif'>Your goal:</span> explore, solve puzzles and find a way out… before it's too late.",
  'cp_p1t'=>"EXPLORE", 'cp_p1d'=>"Roam immersive, creepy rooms; every detail could be a clue.",
  'cp_p2t'=>"SOLVE", 'cp_p2d'=>"Take on logic challenges, observe your surroundings and work together to progress.",
  'cp_p3t'=>"SURVIVE", 'cp_p3d'=>"Something lurks in the Backrooms… stay alert and don't make needless noise.",
  'cp_p4t'=>"ESCAPE", 'cp_p4d'=>"Find the exit before time runs out and etch your feat into the real world.",
  'cp_s2t'=>"WHAT AWAITS YOU", 'cp_s2sub'=>"What will we do during the escape game?",
  'cp_m1t'=>"Total immersion", 'cp_m1d'=>"Realistic sets and an oppressive soundscape for an unforgettable experience.",
  'cp_m2t'=>"Team challenges", 'cp_m2d'=>"Observation, logic and communication are key to moving forward together.",
  'cp_m3t'=>"Guaranteed thrills", 'cp_m3d'=>"Unexpected encounters with « entities » that will test your nerves.",
  'cp_m4t'=>"Free exploration", 'cp_m4d'=>"Search every corner: the smallest detail may hide a crucial clue.",
  'cp_m5t'=>"Race against time", 'cp_m5d'=>"4 to 5 hours to escape… the clock works against you, every second.",
  'cp_s3t'=>"STATISTICS", 'cp_s3sub'=>"Is the escape game easy?",
  'cp_st1'=>"Maximum time to escape", 'cp_st2'=>"Players per team", 'cp_st3'=>"Rooms to explore", 'cp_st4'=>"Success rate", 'cp_st5'=>"Adrenaline guaranteed",
  'cp_classlink'=>"SEE THE TEAM LEADERBOARD &gt;",
  'cp_s4t'=>"THE RULES", 'cp_s4sub'=>"What are the rules?", 'cp_rtitle'=>"Survival rules",
  'cp_r1'=>"Never split from your team.", 'cp_r2'=>"If you hear something unusual, stay silent.", 'cp_r3'=>"Every detail around you may be a clue.", 'cp_r4'=>"Time is against you, stay focused.", 'cp_r5'=>"Some doors should not be opened.",
  'cp_allrules'=>"SEE ALL THE RULES &gt;", 'cp_avist'=>"THEY SURVIVED", 'cp_avissub'=>"… and they tell the tale",
  'rg_title'=>"GAME RULES", 'rg_sub'=>"So the experience stays intense and safe for everyone.",
  'rg_alerte'=>"The stop word <strong>« LIGHT »</strong> instantly ends the game, at any moment and with no need to explain.",
  'rg_c1t'=>"Before the game", 'rg_c1a'=>"Arrive <strong>30 minutes before</strong> your session time.", 'rg_c1b'=>"Minimum age by room: <strong>10</strong> (Room 1), <strong>14</strong> (Room 2), <strong>16</strong> (Room 3).", 'rg_c1c'=>"Teams of <strong>2 to 10 players</strong>.", 'rg_c1d'=>"A locker is provided for your belongings: phones and smartwatches stay inside.",
  'rg_c2t'=>"During the immersion", 'rg_c2a'=>"No photos or videos (to preserve the mystery and the puzzles).", 'rg_c2b'=>"Stay together: splitting up wastes precious time.", 'rg_c2c'=>"Handle the sets with care, never force a mechanism.", 'rg_c2d'=>"A <strong>hint</strong> can be requested at any time via the provided walkie-talkie.",
  'rg_c3t'=>"Safety", 'rg_c3a'=>"The stop word « <strong>LIGHT</strong> » instantly ends the game.", 'rg_c3b'=>"Emergency exits are marked and always accessible.", 'rg_c3c'=>"A game-master actor discreetly watches over you throughout.", 'rg_c3d'=>"Forbidden to anyone under the influence of alcohol or drugs.",
  'rg_c4t'=>"The score", 'rg_c4a'=>"The goal: <strong>« escape the Backrooms »</strong> before time runs out.", 'rg_c4b'=>"Bonus points reward puzzles solved without a hint.", 'rg_c4c'=>"Your escape time and score appear in your private area.", 'rg_c4d'=>"The best teams join the public leaderboard.",
  'rg_cta'=>"Ready to take on the challenge?",
  'ct_title'=>"CONTACT US", 'ct_sub'=>"A question about the experience? Write to us, we reply quickly.",
  'ct_nom'=>"Your name *", 'ct_email'=>"Your email *", 'ct_sujet'=>"Subject *", 'ct_msg'=>"Message *", 'ct_send'=>"Send message",
  'ct_iadr'=>"Address", 'ct_itel'=>"Phone", 'ct_ihor'=>"Opening hours", 'ct_ires'=>"Social media",
 ],
 'es' => [
  'cp_sub'=>"El principio del escape game nocturno",
  'cp_lead'=>"Tú y tu equipo despertáis en las <strong>Backrooms</strong>, un laberinto infinito de salas decrépitas donde la realidad parece desmoronarse.<br><span class='lead-objectif'>Vuestro objetivo:</span> explorar, resolver enigmas y encontrar la manera de escapar… antes de que sea demasiado tarde.",
  'cp_p1t'=>"EXPLORAR", 'cp_p1d'=>"Recorred salas inmersivas y aterradoras; cada detalle puede ser una pista.",
  'cp_p2t'=>"RESOLVER", 'cp_p2d'=>"Enfrentad retos de lógica, observad el entorno y colaborad para avanzar.",
  'cp_p3t'=>"SOBREVIVIR", 'cp_p3d'=>"Algo acecha en las Backrooms… permaneced atentos y no hagáis ruido innecesario.",
  'cp_p4t'=>"ESCAPAR", 'cp_p4d'=>"Encontrad la salida antes de que se acabe el tiempo e inscribid vuestra hazaña en el mundo real.",
  'cp_s2t'=>"LO QUE TE ESPERA", 'cp_s2sub'=>"¿Qué haremos durante el escape game?",
  'cp_m1t'=>"Inmersión total", 'cp_m1d'=>"Decorados realistas y un ambiente sonoro opresivo para una experiencia inolvidable.",
  'cp_m2t'=>"Pruebas en equipo", 'cp_m2d'=>"Observación, lógica y comunicación serán esenciales para avanzar juntos.",
  'cp_m3t'=>"Emoción garantizada", 'cp_m3d'=>"Encuentros inesperados con « entidades » que pondrán a prueba vuestros nervios.",
  'cp_m4t'=>"Exploración libre", 'cp_m4d'=>"Registrad cada rincón: el menor detalle puede ocultar una pista crucial.",
  'cp_m5t'=>"Contrarreloj", 'cp_m5d'=>"4 a 5 horas para escapar… el reloj juega en vuestra contra, cada segundo.",
  'cp_s3t'=>"ESTADÍSTICAS", 'cp_s3sub'=>"¿El escape game es fácil?",
  'cp_st1'=>"Tiempo máximo para escapar", 'cp_st2'=>"Jugadores por equipo", 'cp_st3'=>"Salas para explorar", 'cp_st4'=>"Tasa de éxito", 'cp_st5'=>"Adrenalina garantizada",
  'cp_classlink'=>"VER LA CLASIFICACIÓN DE EQUIPOS &gt;",
  'cp_s4t'=>"LAS REGLAS", 'cp_s4sub'=>"¿Cuáles son las reglas?", 'cp_rtitle'=>"Reglas de supervivencia",
  'cp_r1'=>"No os separéis nunca de vuestro equipo.", 'cp_r2'=>"Si oís algo inusual, guardad silencio.", 'cp_r3'=>"Cada detalle del entorno puede ser una pista.", 'cp_r4'=>"El tiempo juega en vuestra contra, mantened la concentración.", 'cp_r5'=>"Algunas puertas no deberían abrirse.",
  'cp_allrules'=>"VER TODAS LAS REGLAS &gt;", 'cp_avist'=>"SOBREVIVIERON", 'cp_avissub'=>"… y lo cuentan",
  'rg_title'=>"REGLAS DEL JUEGO", 'rg_sub'=>"Para que la experiencia siga siendo intensa y segura para todos.",
  'rg_alerte'=>"La palabra de parada <strong>« LUZ »</strong> termina la partida al instante, en cualquier momento y sin justificación.",
  'rg_c1t'=>"Antes de la partida", 'rg_c1a'=>"Preséntate <strong>30 minutos antes</strong> de la hora de tu sesión.", 'rg_c1b'=>"Edad mínima según la sala: <strong>10 años</strong> (Sala 1), <strong>14 años</strong> (Sala 2), <strong>16 años</strong> (Sala 3).", 'rg_c1c'=>"Equipos de <strong>2 a 10 jugadores</strong>.", 'rg_c1d'=>"Taquilla disponible para tus efectos: móviles y relojes conectados se quedan dentro.",
  'rg_c2t'=>"Durante la inmersión", 'rg_c2a'=>"Ni fotos ni vídeos (para preservar el misterio y los enigmas).", 'rg_c2b'=>"Permaneced en grupo: separarse hace perder un tiempo valioso.", 'rg_c2c'=>"Manipulad los decorados con cuidado, no forcéis nunca un mecanismo.", 'rg_c2d'=>"Se puede pedir una <strong>pista</strong> en cualquier momento con el walkie facilitado.",
  'rg_c3t'=>"Seguridad", 'rg_c3a'=>"La palabra « <strong>LUZ</strong> » termina la partida al instante.", 'rg_c3b'=>"Salidas de emergencia señalizadas y accesibles en todo momento.", 'rg_c3c'=>"Un actor-máster del juego os vigila discretamente todo el rato.", 'rg_c3d'=>"Prohibido a personas bajo los efectos del alcohol o estupefacientes.",
  'rg_c4t'=>"La puntuación", 'rg_c4a'=>"El objetivo: <strong>« salir de las Backrooms »</strong> antes de que se acabe el tiempo.", 'rg_c4b'=>"Puntos extra recompensan los enigmas resueltos sin pista.", 'rg_c4c'=>"Tu tiempo de salida y tu puntuación aparecen en tu espacio privado.", 'rg_c4d'=>"Los mejores equipos entran en la clasificación pública.",
  'rg_cta'=>"¿Listo para intentar la experiencia?",
  'ct_title'=>"CONTÁCTANOS", 'ct_sub'=>"¿Una pregunta sobre la experiencia? Escríbenos, respondemos rápido.",
  'ct_nom'=>"Tu nombre *", 'ct_email'=>"Tu correo *", 'ct_sujet'=>"Asunto *", 'ct_msg'=>"Mensaje *", 'ct_send'=>"Enviar el mensaje",
  'ct_iadr'=>"Dirección", 'ct_itel'=>"Teléfono", 'ct_ihor'=>"Horario", 'ct_ires'=>"Redes sociales",
 ],
];
foreach ($__pages as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Page Infos pratiques ---
$__ip = [
 'fr' => [
  'ip_sub'=>"Tout ce qu'il faut savoir avant de venir",
  'ql_loc'=>"Localisation", 'ql_contact'=>"Contact", 'ql_tarifs'=>"Tarifs", 'ql_heb'=>"Hébergement", 'ql_int'=>"Interdictions",
  'ip_loc_t'=>"LOCALISATION", 'ip_loc_sub'=>"Où se situe notre escape game ?", 'lbl_adresse'=>"Adresse", 'lbl_ville'=>"Ville", 'lbl_cp'=>"Code postal",
  'ip_ct_t'=>"CONTACT", 'ip_ct_sub'=>"Comment nous contacter ?", 'lbl_mail'=>"Adresse mail", 'lbl_tel'=>"Numéro de téléphone", 'lbl_res'=>"Réseaux sociaux",
  'ph_nom'=>"Nom *", 'ph_email'=>"Email *", 'ph_tel'=>"Téléphone", 'ph_msg'=>"Votre message *", 'btn_envoyer'=>"ENVOYER",
  'ip_tar_t'=>"TARIFS", 'ip_tar_sub'=>"Combien coûte une partie ? (4h+ de jeu, repas et nuit sur place inclus)",
  'th_part'=>"Participants", 'th_prix'=>"Prix / personne",
  'tar_r1'=>"2 personnes", 'tar_r2'=>"3 personnes", 'tar_r3'=>"4 personnes", 'tar_r4'=>"5 personnes", 'tar_r5'=>"6 personnes", 'tar_r6'=>"7 à 10 personnes",
  'tar_note'=>"Salle <strong>Hardcore</strong> (5h) : majoration de <strong>+10 €/personne</strong>.<br>Aucun tarif étudiant.",
  'calc_titre'=>"Estimez votre tarif", 'calc_salle'=>"Salle", 'calc_o1'=>"Salle 1 — Facile", 'calc_o2'=>"Salle 2 — Standard", 'calc_o3'=>"Salle 3 — Hardcore (+10 €/pers)",
  'calc_nb'=>"Nombre de participants (2 à 10)", 'calc_err'=>"Indiquez de 2 à 10 participants.", 'calc_unit'=>" € / personne", 'calc_total'=>"Total : ",
  'ip_heb_t'=>"HÉBERGEMENT & RESTAURATION", 'ip_heb_sub'=>"L'immersion continue toute la nuit",
  'heb1_t'=>"La chambre", 'heb1_d'=>"Chambre double (lit séparable), volontairement nue : ni télé, ni table, ni mobilier superflu — 10 m² maximum, pour rester fidèle à l'ambiance liminale.",
  'heb2_t'=>"La restauration", 'heb2_d'=>"Rations de survie thématiques et la fameuse boisson « Eau d'Amande », tout droit sorties du lore des Backrooms.",
  'heb3_t'=>"Le petit-déjeuner", 'heb3_d'=>"<strong>Offert</strong> si votre équipe s'échappe ! En cas d'échec, il vous sera facturé <strong>6 €</strong>… une motivation de plus pour sortir.",
  'ip_int_t'=>"INTERDICTIONS", 'ip_int_sub'=>"Pour la sécurité et le bon déroulement de la partie, ces objets sont interdits :",
  'int1'=>"Téléphone portable", 'int2'=>"Nourriture", 'int3'=>"Arme à feu", 'int4'=>"Cigarette", 'int5'=>"Bombe", 'int6'=>"Arme blanche", 'int7'=>"Animaux", 'int8'=>"Parapluie",
 ],
 'en' => [
  'ip_sub'=>"Everything you need to know before coming",
  'ql_loc'=>"Location", 'ql_contact'=>"Contact", 'ql_tarifs'=>"Prices", 'ql_heb'=>"Accommodation", 'ql_int'=>"Prohibited items",
  'ip_loc_t'=>"LOCATION", 'ip_loc_sub'=>"Where is our escape game?", 'lbl_adresse'=>"Address", 'lbl_ville'=>"City", 'lbl_cp'=>"Postcode",
  'ip_ct_t'=>"CONTACT", 'ip_ct_sub'=>"How to reach us?", 'lbl_mail'=>"Email address", 'lbl_tel'=>"Phone number", 'lbl_res'=>"Social media",
  'ph_nom'=>"Name *", 'ph_email'=>"Email *", 'ph_tel'=>"Phone", 'ph_msg'=>"Your message *", 'btn_envoyer'=>"SEND",
  'ip_tar_t'=>"PRICES", 'ip_tar_sub'=>"How much is a game? (4h+ of play, meal and overnight stay included)",
  'th_part'=>"Participants", 'th_prix'=>"Price / person",
  'tar_r1'=>"2 people", 'tar_r2'=>"3 people", 'tar_r3'=>"4 people", 'tar_r4'=>"5 people", 'tar_r5'=>"6 people", 'tar_r6'=>"7 to 10 people",
  'tar_note'=>"<strong>Hardcore</strong> room (5h): surcharge of <strong>+€10/person</strong>.<br>No student rate.",
  'calc_titre'=>"Estimate your price", 'calc_salle'=>"Room", 'calc_o1'=>"Room 1 — Easy", 'calc_o2'=>"Room 2 — Standard", 'calc_o3'=>"Room 3 — Hardcore (+€10/person)",
  'calc_nb'=>"Number of participants (2 to 10)", 'calc_err'=>"Enter 2 to 10 participants.", 'calc_unit'=>" € / person", 'calc_total'=>"Total: ",
  'ip_heb_t'=>"ACCOMMODATION & FOOD", 'ip_heb_sub'=>"The immersion continues all night",
  'heb1_t'=>"The room", 'heb1_d'=>"Double room (separable bed), deliberately bare: no TV, no table, no superfluous furniture — 10 m² max, to stay true to the liminal mood.",
  'heb2_t'=>"The food", 'heb2_d'=>"Themed survival rations and the famous « Almond Water » drink, straight out of the Backrooms lore.",
  'heb3_t'=>"Breakfast", 'heb3_d'=>"<strong>Free</strong> if your team escapes! If you fail, it will cost you <strong>€6</strong>… one more reason to get out.",
  'ip_int_t'=>"PROHIBITED ITEMS", 'ip_int_sub'=>"For safety and a smooth game, these items are not allowed:",
  'int1'=>"Mobile phone", 'int2'=>"Food", 'int3'=>"Firearm", 'int4'=>"Cigarette", 'int5'=>"Spray can", 'int6'=>"Blade", 'int7'=>"Pets", 'int8'=>"Umbrella",
 ],
 'es' => [
  'ip_sub'=>"Todo lo que hay que saber antes de venir",
  'ql_loc'=>"Ubicación", 'ql_contact'=>"Contacto", 'ql_tarifs'=>"Tarifas", 'ql_heb'=>"Alojamiento", 'ql_int'=>"Prohibiciones",
  'ip_loc_t'=>"UBICACIÓN", 'ip_loc_sub'=>"¿Dónde está nuestro escape game?", 'lbl_adresse'=>"Dirección", 'lbl_ville'=>"Ciudad", 'lbl_cp'=>"Código postal",
  'ip_ct_t'=>"CONTACTO", 'ip_ct_sub'=>"¿Cómo contactarnos?", 'lbl_mail'=>"Correo electrónico", 'lbl_tel'=>"Número de teléfono", 'lbl_res'=>"Redes sociales",
  'ph_nom'=>"Nombre *", 'ph_email'=>"Correo *", 'ph_tel'=>"Teléfono", 'ph_msg'=>"Tu mensaje *", 'btn_envoyer'=>"ENVIAR",
  'ip_tar_t'=>"TARIFAS", 'ip_tar_sub'=>"¿Cuánto cuesta una partida? (4h+ de juego, comida y noche incluidas)",
  'th_part'=>"Participantes", 'th_prix'=>"Precio / persona",
  'tar_r1'=>"2 personas", 'tar_r2'=>"3 personas", 'tar_r3'=>"4 personas", 'tar_r4'=>"5 personas", 'tar_r5'=>"6 personas", 'tar_r6'=>"7 a 10 personas",
  'tar_note'=>"Sala <strong>Hardcore</strong> (5h): recargo de <strong>+10 €/persona</strong>.<br>Sin tarifa de estudiante.",
  'calc_titre'=>"Calcula tu tarifa", 'calc_salle'=>"Sala", 'calc_o1'=>"Sala 1 — Fácil", 'calc_o2'=>"Sala 2 — Estándar", 'calc_o3'=>"Sala 3 — Hardcore (+10 €/pers)",
  'calc_nb'=>"Número de participantes (2 a 10)", 'calc_err'=>"Indica de 2 a 10 participantes.", 'calc_unit'=>" € / persona", 'calc_total'=>"Total: ",
  'ip_heb_t'=>"ALOJAMIENTO Y COMIDA", 'ip_heb_sub'=>"La inmersión continúa toda la noche",
  'heb1_t'=>"La habitación", 'heb1_d'=>"Habitación doble (cama separable), deliberadamente desnuda: ni tele, ni mesa, ni mobiliario superfluo — 10 m² máximo, para ser fiel al ambiente liminal.",
  'heb2_t'=>"La comida", 'heb2_d'=>"Raciones de supervivencia temáticas y la famosa bebida « Agua de Almendra », salidas del lore de las Backrooms.",
  'heb3_t'=>"El desayuno", 'heb3_d'=>"<strong>Gratis</strong> si tu equipo escapa. Si fallas, se te cobrará <strong>6 €</strong>… una motivación más para salir.",
  'ip_int_t'=>"PROHIBICIONES", 'ip_int_sub'=>"Por seguridad y para el buen desarrollo de la partida, estos objetos están prohibidos:",
  'int1'=>"Teléfono móvil", 'int2'=>"Comida", 'int3'=>"Arma de fuego", 'int4'=>"Cigarrillo", 'int5'=>"Aerosol", 'int6'=>"Arma blanca", 'int7'=>"Animales", 'int8'=>"Paraguas",
 ],
];
foreach ($__ip as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Classement + comptes + profil (avis / mot de passe) ---
$__cpt = [
 'fr' => [
  'cl_title'=>"CLASSEMENT", 'cl_sub'=>"Les équipes qui ont survécu aux Backrooms… ou presque.",
  'cl_empty'=>"Aucune partie jouée pour le moment. Le classement apparaîtra après les premières sessions !",
  'cl_equipe'=>"Équipe", 'cl_points'=>"Points", 'cl_temps'=>"Meilleur temps", 'cl_parties'=>"Parties", 'cl_sorties'=>"Sorties",
  'cl_cta'=>"Votre équipe peut faire mieux ?", 'cl_cta_btn'=>"DÉFIER LES BACKROOMS",
  'lg_co_title'=>"Connexion", 'lg_email'=>"Email", 'lg_pass'=>"Mot de passe", 'lg_co_btn'=>"Se connecter",
  'lg_no_acct'=>"Pas encore de compte ?", 'lg_create'=>"Créez-en un", 'lg_forgot'=>"Mot de passe oublié ?",
  'lg_in_title'=>"Inscription", 'lg_nom'=>"Nom *", 'lg_prenom'=>"Prénom *", 'lg_pseudo'=>"Pseudo *", 'lg_email_r'=>"Email *", 'lg_tel'=>"Téléphone", 'lg_pass_r'=>"Mot de passe *", 'lg_in_btn'=>"S'inscrire", 'lg_already'=>"Déjà inscrit ?", 'lg_login_link'=>"Connectez-vous",
  'lg_fg_title'=>"Mot de passe oublié", 'lg_fg_txt'=>"Saisissez votre adresse email : nous vous enverrons un lien pour choisir un nouveau mot de passe.", 'lg_fg_btn'=>"Envoyer le lien", 'lg_back_login'=>"‹ Retour à la connexion",
  'lg_rs_title'=>"Nouveau mot de passe", 'lg_rs_new'=>"Nouveau mot de passe (6 caractères min.)", 'lg_rs_confirm'=>"Confirmez le mot de passe", 'lg_rs_btn'=>"Changer le mot de passe", 'lg_redo'=>"Refaire une demande", 'lg_rs_login'=>"Se connecter",
  'pr_title'=>"Mon Profil", 'pr_tab_infos'=>"Informations personnelles", 'pr_tab_pass'=>"Mot de passe", 'pr_tab_avis'=>"Laisser un avis", 'pr_logout'=>"Déconnexion",
  'av_intro'=>"Avez-vous réussi à sortir des Backrooms ? Laissez-nous votre avis sur l'expérience !", 'av_note'=>"Note (sur 5) *",
  'av_o5'=>"5 - Excellent, inoubliable !", 'av_o4'=>"4 - Très bien, angoissant", 'av_o3'=>"3 - Bien, mais peut mieux faire", 'av_o2'=>"2 - Décevant", 'av_o1'=>"1 - Très mauvais",
  'av_txt'=>"Votre commentaire *", 'av_btn'=>"Envoyer mon avis",
  'pw_actuel'=>"Mot de passe actuel *", 'pw_nouveau'=>"Nouveau mot de passe *", 'pw_confirm'=>"Confirmer le nouveau mot de passe *", 'pw_btn'=>"Modifier le mot de passe",
 ],
 'en' => [
  'cl_title'=>"LEADERBOARD", 'cl_sub'=>"The teams that survived the Backrooms… or almost.",
  'cl_empty'=>"No game played yet. The leaderboard will appear after the first sessions!",
  'cl_equipe'=>"Team", 'cl_points'=>"Points", 'cl_temps'=>"Best time", 'cl_parties'=>"Games", 'cl_sorties'=>"Escapes",
  'cl_cta'=>"Can your team do better?", 'cl_cta_btn'=>"CHALLENGE THE BACKROOMS",
  'lg_co_title'=>"Log in", 'lg_email'=>"Email", 'lg_pass'=>"Password", 'lg_co_btn'=>"Log in",
  'lg_no_acct'=>"No account yet?", 'lg_create'=>"Create one", 'lg_forgot'=>"Forgot password?",
  'lg_in_title'=>"Sign up", 'lg_nom'=>"Last name *", 'lg_prenom'=>"First name *", 'lg_pseudo'=>"Username *", 'lg_email_r'=>"Email *", 'lg_tel'=>"Phone", 'lg_pass_r'=>"Password *", 'lg_in_btn'=>"Sign up", 'lg_already'=>"Already registered?", 'lg_login_link'=>"Log in",
  'lg_fg_title'=>"Forgot password", 'lg_fg_txt'=>"Enter your email address: we'll send you a link to choose a new password.", 'lg_fg_btn'=>"Send the link", 'lg_back_login'=>"‹ Back to login",
  'lg_rs_title'=>"New password", 'lg_rs_new'=>"New password (6 characters min.)", 'lg_rs_confirm'=>"Confirm the password", 'lg_rs_btn'=>"Change password", 'lg_redo'=>"Request again", 'lg_rs_login'=>"Log in",
  'pr_title'=>"My Profile", 'pr_tab_infos'=>"Personal information", 'pr_tab_pass'=>"Password", 'pr_tab_avis'=>"Leave a review", 'pr_logout'=>"Log out",
  'av_intro'=>"Did you manage to escape the Backrooms? Leave us your review of the experience!", 'av_note'=>"Rating (out of 5) *",
  'av_o5'=>"5 - Excellent, unforgettable!", 'av_o4'=>"4 - Very good, scary", 'av_o3'=>"3 - Good, but could be better", 'av_o2'=>"2 - Disappointing", 'av_o1'=>"1 - Very bad",
  'av_txt'=>"Your comment *", 'av_btn'=>"Send my review",
  'pw_actuel'=>"Current password *", 'pw_nouveau'=>"New password *", 'pw_confirm'=>"Confirm the new password *", 'pw_btn'=>"Change password",
 ],
 'es' => [
  'cl_title'=>"CLASIFICACIÓN", 'cl_sub'=>"Los equipos que sobrevivieron a las Backrooms… o casi.",
  'cl_empty'=>"Aún no se ha jugado ninguna partida. ¡La clasificación aparecerá tras las primeras sesiones!",
  'cl_equipe'=>"Equipo", 'cl_points'=>"Puntos", 'cl_temps'=>"Mejor tiempo", 'cl_parties'=>"Partidas", 'cl_sorties'=>"Salidas",
  'cl_cta'=>"¿Tu equipo puede hacerlo mejor?", 'cl_cta_btn'=>"DESAFÍA LAS BACKROOMS",
  'lg_co_title'=>"Iniciar sesión", 'lg_email'=>"Correo", 'lg_pass'=>"Contraseña", 'lg_co_btn'=>"Iniciar sesión",
  'lg_no_acct'=>"¿Aún no tienes cuenta?", 'lg_create'=>"Crea una", 'lg_forgot'=>"¿Olvidaste tu contraseña?",
  'lg_in_title'=>"Registro", 'lg_nom'=>"Apellido *", 'lg_prenom'=>"Nombre *", 'lg_pseudo'=>"Usuario *", 'lg_email_r'=>"Correo *", 'lg_tel'=>"Teléfono", 'lg_pass_r'=>"Contraseña *", 'lg_in_btn'=>"Registrarse", 'lg_already'=>"¿Ya registrado?", 'lg_login_link'=>"Inicia sesión",
  'lg_fg_title'=>"Contraseña olvidada", 'lg_fg_txt'=>"Introduce tu correo: te enviaremos un enlace para elegir una nueva contraseña.", 'lg_fg_btn'=>"Enviar el enlace", 'lg_back_login'=>"‹ Volver al inicio de sesión",
  'lg_rs_title'=>"Nueva contraseña", 'lg_rs_new'=>"Nueva contraseña (mín. 6 caracteres)", 'lg_rs_confirm'=>"Confirma la contraseña", 'lg_rs_btn'=>"Cambiar la contraseña", 'lg_redo'=>"Volver a solicitar", 'lg_rs_login'=>"Iniciar sesión",
  'pr_title'=>"Mi Perfil", 'pr_tab_infos'=>"Información personal", 'pr_tab_pass'=>"Contraseña", 'pr_tab_avis'=>"Dejar una reseña", 'pr_logout'=>"Cerrar sesión",
  'av_intro'=>"¿Conseguiste salir de las Backrooms? ¡Déjanos tu reseña de la experiencia!", 'av_note'=>"Nota (sobre 5) *",
  'av_o5'=>"5 - ¡Excelente, inolvidable!", 'av_o4'=>"4 - Muy bien, angustiante", 'av_o3'=>"3 - Bien, pero mejorable", 'av_o2'=>"2 - Decepcionante", 'av_o1'=>"1 - Muy malo",
  'av_txt'=>"Tu comentario *", 'av_btn'=>"Enviar mi reseña",
  'pw_actuel'=>"Contraseña actual *", 'pw_nouveau'=>"Nueva contraseña *", 'pw_confirm'=>"Confirmar la nueva contraseña *", 'pw_btn'=>"Cambiar la contraseña",
 ],
];
foreach ($__cpt as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

function lang_courante() { return $GLOBALS['LANG']; }
