<?php
/**
 * Internationalisation (i18n) — FR par défaut, + EN et ES.
 * La langue est mémorisée en session et se change via ?lang=xx.
 * Pour ajouter une langue : l'ajouter à $dispo et compléter $TRAD.
 */
$dispo = ['fr', 'en', 'es'];
if (isset($_GET['lang']) && in_array($_GET['lang'], $dispo, true)) {
    $_SESSION['lang'] = $_GET['lang'];
}
$GLOBALS['LANG'] = (isset($_SESSION['lang']) && in_array($_SESSION['lang'], $dispo, true)) ? $_SESSION['lang'] : 'fr';

$GLOBALS['TRAD'] = [
 'fr' => [
  'nav_accueil'=>"ACCUEIL", 'nav_concept'=>"CONCEPT", 'nav_salles'=>"LES SALLES",
  'nav_infos'=>"INFOS PRATIQUES", 'nav_regles'=>"RÈGLES", 'nav_contact'=>"CONTACT", 'nav_classement'=>"Classement",
  'btn_reserver'=>"RÉSERVER", 'btn_espace'=>"MON ESPACE", 'btn_connexion'=>"Connexion",
  'foot_tagline'=>"Escape game nocturne immersif.",
  'foot_quote'=>"«&nbsp;Vous n'auriez jamais dû trouver cet endroit.&nbsp;»",
  'foot_h_nav'=>"Navigation", 'foot_h_infos'=>"Infos pratiques", 'foot_h_pret'=>"Prêt·e&nbsp;?",
  'foot_resa_txt'=>"Réservez votre nuit dans les Backrooms.", 'foot_contact'=>"Nous contacter",
  'foot_jours'=>"Vendredi soir, samedi soir, jours fériés et vacances scolaires (sauf le lundi)",
  'foot_rights'=>"Tous droits réservés.", 'foot_by'=>"Réalisé par",
  'home_intro'=>"Inspiré de la légende urbaine des Backrooms, une dimension parallèle angoissante accessible uniquement par un « bug de la réalité », notre concept exploite la psychologie des espaces liminaux : des lieux de transition vides, répétitifs et vaguement familiers, qui génèrent un sentiment d'isolement et d'étrangeté. L'expérience se déroule du soir (19h-20h) au lendemain matin, avec 4 heures de jeu effectif pour tenter de « sortir des Backrooms ». Les décors immersifs et nos comédiens rendent cette expérience inoubliable !",
  'home_btn_reserver'=>"RÉSERVER UNE SESSION", 'home_btn_plus'=>"EN SAVOIR PLUS &gt;",
  'feat_entrer'=>"ENTRER DANS<br>LES BACKROOMS &gt;", 'feat_joueurs'=>"JOUEURS &gt;", 'feat_regles'=>"RÈGLES &gt;",
  'video_titre'=>"LA BANDE-ANNONCE", 'video_sous'=>"Plongez dans l'ambiance avant de franchir la porte.",
 ],
 'en' => [
  'nav_accueil'=>"HOME", 'nav_concept'=>"CONCEPT", 'nav_salles'=>"THE ROOMS",
  'nav_infos'=>"VISITOR INFO", 'nav_regles'=>"RULES", 'nav_contact'=>"CONTACT", 'nav_classement'=>"Leaderboard",
  'btn_reserver'=>"BOOK NOW", 'btn_espace'=>"MY ACCOUNT", 'btn_connexion'=>"Log in",
  'foot_tagline'=>"Immersive nighttime escape game.",
  'foot_quote'=>"«&nbsp;You should never have found this place.&nbsp;»",
  'foot_h_nav'=>"Navigation", 'foot_h_infos'=>"Visitor info", 'foot_h_pret'=>"Ready?",
  'foot_resa_txt'=>"Book your night in the Backrooms.", 'foot_contact'=>"Contact us",
  'foot_jours'=>"Friday & Saturday evenings, public holidays and school holidays (except Mondays)",
  'foot_rights'=>"All rights reserved.", 'foot_by'=>"Made by",
  'home_intro'=>"Inspired by the urban legend of the Backrooms — an unsettling parallel dimension reachable only through a « glitch in reality » — our concept plays on the psychology of liminal spaces: empty, repetitive, vaguely familiar in-between places that create a feeling of isolation and unease. The experience runs from the evening (7–8 pm) until the next morning, with 4 hours of actual gameplay to try to « escape the Backrooms ». Immersive sets and our live actors make it unforgettable!",
  'home_btn_reserver'=>"BOOK A SESSION", 'home_btn_plus'=>"LEARN MORE &gt;",
  'feat_entrer'=>"ENTER THE<br>BACKROOMS &gt;", 'feat_joueurs'=>"PLAYERS &gt;", 'feat_regles'=>"RULES &gt;",
  'video_titre'=>"THE TRAILER", 'video_sous'=>"Get a taste of the atmosphere before you step through the door.",
 ],
 'es' => [
  'nav_accueil'=>"INICIO", 'nav_concept'=>"CONCEPTO", 'nav_salles'=>"LAS SALAS",
  'nav_infos'=>"INFO PRÁCTICA", 'nav_regles'=>"REGLAS", 'nav_contact'=>"CONTACTO", 'nav_classement'=>"Clasificación",
  'btn_reserver'=>"RESERVAR", 'btn_espace'=>"MI ESPACIO", 'btn_connexion'=>"Iniciar sesión",
  'foot_tagline'=>"Escape game nocturno inmersivo.",
  'foot_quote'=>"«&nbsp;Nunca deberías haber encontrado este lugar.&nbsp;»",
  'foot_h_nav'=>"Navegación", 'foot_h_infos'=>"Info práctica", 'foot_h_pret'=>"¿Listo?",
  'foot_resa_txt'=>"Reserva tu noche en las Backrooms.", 'foot_contact'=>"Contáctanos",
  'foot_jours'=>"Viernes y sábados por la noche, festivos y vacaciones escolares (excepto lunes)",
  'foot_rights'=>"Todos los derechos reservados.", 'foot_by'=>"Hecho por",
  'home_intro'=>"Inspirado en la leyenda urbana de las Backrooms — una inquietante dimensión paralela a la que solo se accede por un « fallo de la realidad » — nuestro concepto juega con la psicología de los espacios liminales: lugares de paso vacíos, repetitivos y vagamente familiares que provocan una sensación de aislamiento y extrañeza. La experiencia transcurre desde la tarde (19-20 h) hasta la mañana siguiente, con 4 horas de juego efectivo para intentar « salir de las Backrooms ». ¡Los decorados inmersivos y nuestros actores la hacen inolvidable!",
  'home_btn_reserver'=>"RESERVAR UNA SESIÓN", 'home_btn_plus'=>"SABER MÁS &gt;",
  'feat_entrer'=>"ENTRAR EN<br>LAS BACKROOMS &gt;", 'feat_joueurs'=>"JUGADORES &gt;", 'feat_regles'=>"REGLAS &gt;",
  'video_titre'=>"EL TRÁILER", 'video_sous'=>"Sumérgete en el ambiente antes de cruzar la puerta.",
 ],
];

function t($k) {
    $l = $GLOBALS['LANG'];
    return $GLOBALS['TRAD'][$l][$k] ?? ($GLOBALS['TRAD']['fr'][$k] ?? $k);
}
// --- Page « Les salles » ---
$__salles = [
 'fr' => [
  'sl_sub'=>"Trois niveaux de difficulté, une seule promesse : vous faire perdre la notion du temps.",
  's1_tag'=>"FACILE", 's1_nom'=>"Le Niveau 0",
  's1_desc'=>"Exploration et cartographie, sans aucune menace. Décors jaunes, moquette humide, néons qui bourdonnent et une salle « supermarché ». Idéale en famille.",
  's1_a'=>"4 h de jeu + repas et nuit sur place", 's1_b'=>"2 à 10 joueurs", 's1_c'=>"Dès 10 ans", 's1_d'=>"Aucun comédien — ambiance contemplative", 's1_prix'=>"À partir de 145 €/pers",
  's2_tag'=>"STANDARD", 's2_nom'=>"Les Couloirs jaunes",
  's2_desc'=>"Entrepôt sombre, tuyauteries et coupures de courant : gestion du stress et recherche de ressources, avec l'intervention de comédiens (les entités).",
  's2_a'=>"4 h de jeu + repas et nuit sur place", 's2_b'=>"2 à 10 joueurs", 's2_c'=>"Dès 14 ans", 's2_d'=>"Présence de comédiens — montée d'adrénaline", 's2_prix'=>"À partir de 145 €/pers",
  's3_tag'=>"HARDCORE", 's3_nom'=>"Le Niveau !",
  's3_desc'=>"Noir complet, signaux d'alarme, stimuli sonores agressifs et traque ininterrompue par les entités. Pour les plus téméraires — le mot « LUMIÈRE » sera tentant…",
  's3_a'=>"5 h de jeu + repas et nuit sur place", 's3_b'=>"2 à 10 joueurs", 's3_c'=>"Dès 16 ans", 's3_d'=>"Horreur extrême — traque continue", 's3_prix'=>"À partir de 155 €/pers",
  'sl_note'=>"Tarif dégressif selon l'effectif — hébergement et repas inclus.",
 ],
 'en' => [
  'sl_sub'=>"Three difficulty levels, one promise: to make you lose all track of time.",
  's1_tag'=>"EASY", 's1_nom'=>"Level 0",
  's1_desc'=>"Exploration and mapping, with no threat at all. Yellow walls, damp carpet, buzzing fluorescent lights and a « supermarket » room. Perfect for families.",
  's1_a'=>"4 hrs of play + meal and overnight stay", 's1_b'=>"2 to 10 players", 's1_c'=>"Ages 10+", 's1_d'=>"No actors — contemplative mood", 's1_prix'=>"From €145/person",
  's2_tag'=>"STANDARD", 's2_nom'=>"The Yellow Corridors",
  's2_desc'=>"Dark warehouse, pipework and power cuts: stress management and resource hunting, with live actors (the entities) stepping in.",
  's2_a'=>"4 hrs of play + meal and overnight stay", 's2_b'=>"2 to 10 players", 's2_c'=>"Ages 14+", 's2_d'=>"Live actors — rising adrenaline", 's2_prix'=>"From €145/person",
  's3_tag'=>"HARDCORE", 's3_nom'=>"Level !",
  's3_desc'=>"Total darkness, alarm signals, aggressive sound stimuli and relentless pursuit by the entities. For the boldest — the word « LIGHT » will be tempting…",
  's3_a'=>"5 hrs of play + meal and overnight stay", 's3_b'=>"2 to 10 players", 's3_c'=>"Ages 16+", 's3_d'=>"Extreme horror — continuous chase", 's3_prix'=>"From €155/person",
  'sl_note'=>"Decreasing rate by group size — accommodation and meals included.",
 ],
 'es' => [
  'sl_sub'=>"Tres niveles de dificultad, una sola promesa: hacerte perder la noción del tiempo.",
  's1_tag'=>"FÁCIL", 's1_nom'=>"El Nivel 0",
  's1_desc'=>"Exploración y cartografía, sin ninguna amenaza. Paredes amarillas, moqueta húmeda, fluorescentes que zumban y una sala « supermercado ». Ideal en familia.",
  's1_a'=>"4 h de juego + comida y noche en el lugar", 's1_b'=>"2 a 10 jugadores", 's1_c'=>"Desde 10 años", 's1_d'=>"Sin actores — ambiente contemplativo", 's1_prix'=>"Desde 145 €/persona",
  's2_tag'=>"ESTÁNDAR", 's2_nom'=>"Los Pasillos Amarillos",
  's2_desc'=>"Almacén oscuro, tuberías y cortes de luz: gestión del estrés y búsqueda de recursos, con la intervención de actores (las entidades).",
  's2_a'=>"4 h de juego + comida y noche en el lugar", 's2_b'=>"2 a 10 jugadores", 's2_c'=>"Desde 14 años", 's2_d'=>"Presencia de actores — sube la adrenalina", 's2_prix'=>"Desde 145 €/persona",
  's3_tag'=>"EXTREMO", 's3_nom'=>"¡El Nivel !",
  's3_desc'=>"Oscuridad total, señales de alarma, estímulos sonoros agresivos y persecución incesante de las entidades. Para los más atrevidos — la palabra « LUZ » será tentadora…",
  's3_a'=>"5 h de juego + comida y noche en el lugar", 's3_b'=>"2 a 10 jugadores", 's3_c'=>"Desde 16 años", 's3_d'=>"Horror extremo — persecución continua", 's3_prix'=>"Desde 155 €/persona",
  'sl_note'=>"Tarifa decreciente según el grupo — alojamiento y comidas incluidos.",
 ],
];
foreach ($__salles as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Pages Concept / Règles / Contact ---
$__pages = [
 'fr' => [
  'cp_sub'=>"Le principe de l'escape game de nuit",
  'cp_lead'=>"Vous et votre équipe vous réveillez dans les <strong>Backrooms</strong>, un labyrinthe infini de pièces décrépites où la réalité semble se déliter.<br><span class='lead-objectif'>Votre objectif :</span> explorer, résoudre des énigmes et trouver le moyen de vous échapper… avant qu'il ne soit trop tard.",
  'cp_p1t'=>"EXPLORER", 'cp_p1d'=>"Parcourez des salles immersives et flippantes ; chaque détail peut être un indice.",
  'cp_p2t'=>"RÉSOUDRE", 'cp_p2d'=>"Affrontez des défis de logique, observez l'environnement et collaborez pour progresser.",
  'cp_p3t'=>"SURVIVRE", 'cp_p3d'=>"Quelque chose rôde dans les Backrooms… restez vigilants et ne faites pas de bruit inutile.",
  'cp_p4t'=>"S'ÉCHAPPER", 'cp_p4d'=>"Trouvez la sortie avant la fin du temps et inscrivez votre exploit dans le monde réel.",
  'cp_s2t'=>"CE QUI VOUS ATTEND", 'cp_s2sub'=>"On va faire quoi pendant l'escape game ?",
  'cp_m1t'=>"Immersion totale", 'cp_m1d'=>"Des décors réalistes et une ambiance sonore oppressante pour une expérience inoubliable.",
  'cp_m2t'=>"Épreuves collaboratives", 'cp_m2d'=>"Observation, logique et communication seront essentielles pour avancer ensemble.",
  'cp_m3t'=>"Frisson garanti", 'cp_m3d'=>"Des rencontres inattendues avec des « entités » qui mettront vos nerfs à rude épreuve.",
  'cp_m4t'=>"Exploration libre", 'cp_m4d'=>"Fouillez chaque recoin : le moindre détail peut cacher un indice crucial.",
  'cp_m5t'=>"Course contre le temps", 'cp_m5d'=>"4 à 5 heures pour vous échapper… le chrono joue contre vous, à chaque seconde.",
  'cp_s3t'=>"STATISTIQUES", 'cp_s3sub'=>"Est-ce que l'escape game est facile ?",
  'cp_st1'=>"Temps maximum pour s'échapper", 'cp_st2'=>"Joueurs par équipe", 'cp_st3'=>"Salles à explorer", 'cp_st4'=>"Taux de réussite", 'cp_st5'=>"Adrénaline garantie",
  'cp_classlink'=>"VOIR LE CLASSEMENT DES ÉQUIPES &gt;",
  'cp_s4t'=>"LES RÈGLES", 'cp_s4sub'=>"Quelles sont les règles ?", 'cp_rtitle'=>"Les règles de survie",
  'cp_r1'=>"Ne vous séparez jamais de votre équipe.", 'cp_r2'=>"Si vous entendez quelque chose d'inhabituel, restez silencieux.", 'cp_r3'=>"Chaque détail de votre environnement peut être un indice.", 'cp_r4'=>"Le temps joue contre vous, restez concentrés.", 'cp_r5'=>"Certaines parties ne devraient pas être ouvertes.",
  'cp_allrules'=>"VOIR TOUTES LES RÈGLES &gt;", 'cp_avist'=>"ILS ONT SURVÉCU", 'cp_avissub'=>"… et ils témoignent",
  'rg_title'=>"RÈGLES DU JEU", 'rg_sub'=>"Pour que l'expérience reste intense et sûre pour tout le monde.",
  'rg_alerte'=>"Le mot d'arrêt <strong>« LUMIÈRE »</strong> met instantanément fin à la partie, à tout moment et sans justification.",
  'rg_c1t'=>"Avant la partie", 'rg_c1a'=>"Présentez-vous <strong>30 minutes avant</strong> l'horaire de votre session.", 'rg_c1b'=>"Âge minimum selon la salle : <strong>10 ans</strong> (Salle 1), <strong>14 ans</strong> (Salle 2), <strong>16 ans</strong> (Salle 3).", 'rg_c1c'=>"Équipes de <strong>2 à 10 joueurs</strong>.", 'rg_c1d'=>"Casier fourni pour vos effets : téléphones et montres connectées y restent.",
  'rg_c2t'=>"Pendant l'immersion", 'rg_c2a'=>"Aucune photo ni vidéo (pour préserver le mystère et les énigmes).", 'rg_c2b'=>"Restez en groupe : se séparer fait perdre un temps précieux.", 'rg_c2c'=>"Manipulez les décors avec soin, ne forcez jamais un mécanisme.", 'rg_c2d'=>"Un <strong>indice</strong> peut être demandé à tout moment via le talkie fourni.",
  'rg_c3t'=>"Sécurité", 'rg_c3a'=>"Le mot d'arrêt « <strong>LUMIÈRE</strong> » met instantanément fin à la partie.", 'rg_c3b'=>"Sorties de secours signalées et accessibles en permanence.", 'rg_c3c'=>"Un comédien-maître du jeu vous surveille discrètement tout du long.", 'rg_c3d'=>"Interdit aux personnes sous l'emprise d'alcool ou de stupéfiants.",
  'rg_c4t'=>"Le score", 'rg_c4a'=>"L'objectif : <strong>« sortir des Backrooms »</strong> avant la fin du temps imparti.", 'rg_c4b'=>"Des points bonus récompensent les énigmes résolues sans indice.", 'rg_c4c'=>"Votre temps de sortie et votre score apparaissent dans votre espace privé.", 'rg_c4d'=>"Les meilleures équipes rejoignent le classement public.",
  'rg_cta'=>"Prêt·e à tenter l'expérience ?",
  'ct_title'=>"NOUS CONTACTER", 'ct_sub'=>"Une question sur l'expérience ? Écrivez-nous, on vous répond rapidement.",
  'ct_nom'=>"Votre nom *", 'ct_email'=>"Votre email *", 'ct_sujet'=>"Sujet *", 'ct_msg'=>"Message *", 'ct_send'=>"Envoyer le message",
  'ct_iadr'=>"Adresse", 'ct_itel'=>"Téléphone", 'ct_ihor'=>"Horaires", 'ct_ires'=>"Réseaux sociaux",
 ],
 'en' => [
  'cp_sub'=>"How the nighttime escape game works",
  'cp_lead'=>"You and your team wake up in the <strong>Backrooms</strong>, an endless maze of decaying rooms where reality seems to fall apart.<br><span class='lead-objectif'>Your goal:</span> explore, solve puzzles and find a way out… before it's too late.",
  'cp_p1t'=>"EXPLORE", 'cp_p1d'=>"Roam immersive, creepy rooms; every detail could be a clue.",
  'cp_p2t'=>"SOLVE", 'cp_p2d'=>"Take on logic challenges, observe your surroundings and work together to progress.",
  'cp_p3t'=>"SURVIVE", 'cp_p3d'=>"Something lurks in the Backrooms… stay alert and don't make needless noise.",
  'cp_p4t'=>"ESCAPE", 'cp_p4d'=>"Find the exit before time runs out and etch your feat into the real world.",
  'cp_s2t'=>"WHAT AWAITS YOU", 'cp_s2sub'=>"What will we do during the escape game?",
  'cp_m1t'=>"Total immersion", 'cp_m1d'=>"Realistic sets and an oppressive soundscape for an unforgettable experience.",
  'cp_m2t'=>"Team challenges", 'cp_m2d'=>"Observation, logic and communication are key to moving forward together.",
  'cp_m3t'=>"Guaranteed thrills", 'cp_m3d'=>"Unexpected encounters with « entities » that will test your nerves.",
  'cp_m4t'=>"Free exploration", 'cp_m4d'=>"Search every corner: the smallest detail may hide a crucial clue.",
  'cp_m5t'=>"Race against time", 'cp_m5d'=>"4 to 5 hours to escape… the clock works against you, every second.",
  'cp_s3t'=>"STATISTICS", 'cp_s3sub'=>"Is the escape game easy?",
  'cp_st1'=>"Maximum time to escape", 'cp_st2'=>"Players per team", 'cp_st3'=>"Rooms to explore", 'cp_st4'=>"Success rate", 'cp_st5'=>"Adrenaline guaranteed",
  'cp_classlink'=>"SEE THE TEAM LEADERBOARD &gt;",
  'cp_s4t'=>"THE RULES", 'cp_s4sub'=>"What are the rules?", 'cp_rtitle'=>"Survival rules",
  'cp_r1'=>"Never split from your team.", 'cp_r2'=>"If you hear something unusual, stay silent.", 'cp_r3'=>"Every detail around you may be a clue.", 'cp_r4'=>"Time is against you, stay focused.", 'cp_r5'=>"Some doors should not be opened.",
  'cp_allrules'=>"SEE ALL THE RULES &gt;", 'cp_avist'=>"THEY SURVIVED", 'cp_avissub'=>"… and they tell the tale",
  'rg_title'=>"GAME RULES", 'rg_sub'=>"So the experience stays intense and safe for everyone.",
  'rg_alerte'=>"The stop word <strong>« LIGHT »</strong> instantly ends the game, at any moment and with no need to explain.",
  'rg_c1t'=>"Before the game", 'rg_c1a'=>"Arrive <strong>30 minutes before</strong> your session time.", 'rg_c1b'=>"Minimum age by room: <strong>10</strong> (Room 1), <strong>14</strong> (Room 2), <strong>16</strong> (Room 3).", 'rg_c1c'=>"Teams of <strong>2 to 10 players</strong>.", 'rg_c1d'=>"A locker is provided for your belongings: phones and smartwatches stay inside.",
  'rg_c2t'=>"During the immersion", 'rg_c2a'=>"No photos or videos (to preserve the mystery and the puzzles).", 'rg_c2b'=>"Stay together: splitting up wastes precious time.", 'rg_c2c'=>"Handle the sets with care, never force a mechanism.", 'rg_c2d'=>"A <strong>hint</strong> can be requested at any time via the provided walkie-talkie.",
  'rg_c3t'=>"Safety", 'rg_c3a'=>"The stop word « <strong>LIGHT</strong> » instantly ends the game.", 'rg_c3b'=>"Emergency exits are marked and always accessible.", 'rg_c3c'=>"A game-master actor discreetly watches over you throughout.", 'rg_c3d'=>"Forbidden to anyone under the influence of alcohol or drugs.",
  'rg_c4t'=>"The score", 'rg_c4a'=>"The goal: <strong>« escape the Backrooms »</strong> before time runs out.", 'rg_c4b'=>"Bonus points reward puzzles solved without a hint.", 'rg_c4c'=>"Your escape time and score appear in your private area.", 'rg_c4d'=>"The best teams join the public leaderboard.",
  'rg_cta'=>"Ready to take on the challenge?",
  'ct_title'=>"CONTACT US", 'ct_sub'=>"A question about the experience? Write to us, we reply quickly.",
  'ct_nom'=>"Your name *", 'ct_email'=>"Your email *", 'ct_sujet'=>"Subject *", 'ct_msg'=>"Message *", 'ct_send'=>"Send message",
  'ct_iadr'=>"Address", 'ct_itel'=>"Phone", 'ct_ihor'=>"Opening hours", 'ct_ires'=>"Social media",
 ],
 'es' => [
  'cp_sub'=>"El principio del escape game nocturno",
  'cp_lead'=>"Tú y tu equipo despertáis en las <strong>Backrooms</strong>, un laberinto infinito de salas decrépitas donde la realidad parece desmoronarse.<br><span class='lead-objectif'>Vuestro objetivo:</span> explorar, resolver enigmas y encontrar la manera de escapar… antes de que sea demasiado tarde.",
  'cp_p1t'=>"EXPLORAR", 'cp_p1d'=>"Recorred salas inmersivas y aterradoras; cada detalle puede ser una pista.",
  'cp_p2t'=>"RESOLVER", 'cp_p2d'=>"Enfrentad retos de lógica, observad el entorno y colaborad para avanzar.",
  'cp_p3t'=>"SOBREVIVIR", 'cp_p3d'=>"Algo acecha en las Backrooms… permaneced atentos y no hagáis ruido innecesario.",
  'cp_p4t'=>"ESCAPAR", 'cp_p4d'=>"Encontrad la salida antes de que se acabe el tiempo e inscribid vuestra hazaña en el mundo real.",
  'cp_s2t'=>"LO QUE TE ESPERA", 'cp_s2sub'=>"¿Qué haremos durante el escape game?",
  'cp_m1t'=>"Inmersión total", 'cp_m1d'=>"Decorados realistas y un ambiente sonoro opresivo para una experiencia inolvidable.",
  'cp_m2t'=>"Pruebas en equipo", 'cp_m2d'=>"Observación, lógica y comunicación serán esenciales para avanzar juntos.",
  'cp_m3t'=>"Emoción garantizada", 'cp_m3d'=>"Encuentros inesperados con « entidades » que pondrán a prueba vuestros nervios.",
  'cp_m4t'=>"Exploración libre", 'cp_m4d'=>"Registrad cada rincón: el menor detalle puede ocultar una pista crucial.",
  'cp_m5t'=>"Contrarreloj", 'cp_m5d'=>"4 a 5 horas para escapar… el reloj juega en vuestra contra, cada segundo.",
  'cp_s3t'=>"ESTADÍSTICAS", 'cp_s3sub'=>"¿El escape game es fácil?",
  'cp_st1'=>"Tiempo máximo para escapar", 'cp_st2'=>"Jugadores por equipo", 'cp_st3'=>"Salas para explorar", 'cp_st4'=>"Tasa de éxito", 'cp_st5'=>"Adrenalina garantizada",
  'cp_classlink'=>"VER LA CLASIFICACIÓN DE EQUIPOS &gt;",
  'cp_s4t'=>"LAS REGLAS", 'cp_s4sub'=>"¿Cuáles son las reglas?", 'cp_rtitle'=>"Reglas de supervivencia",
  'cp_r1'=>"No os separéis nunca de vuestro equipo.", 'cp_r2'=>"Si oís algo inusual, guardad silencio.", 'cp_r3'=>"Cada detalle del entorno puede ser una pista.", 'cp_r4'=>"El tiempo juega en vuestra contra, mantened la concentración.", 'cp_r5'=>"Algunas puertas no deberían abrirse.",
  'cp_allrules'=>"VER TODAS LAS REGLAS &gt;", 'cp_avist'=>"SOBREVIVIERON", 'cp_avissub'=>"… y lo cuentan",
  'rg_title'=>"REGLAS DEL JUEGO", 'rg_sub'=>"Para que la experiencia siga siendo intensa y segura para todos.",
  'rg_alerte'=>"La palabra de parada <strong>« LUZ »</strong> termina la partida al instante, en cualquier momento y sin justificación.",
  'rg_c1t'=>"Antes de la partida", 'rg_c1a'=>"Preséntate <strong>30 minutos antes</strong> de la hora de tu sesión.", 'rg_c1b'=>"Edad mínima según la sala: <strong>10 años</strong> (Sala 1), <strong>14 años</strong> (Sala 2), <strong>16 años</strong> (Sala 3).", 'rg_c1c'=>"Equipos de <strong>2 a 10 jugadores</strong>.", 'rg_c1d'=>"Taquilla disponible para tus efectos: móviles y relojes conectados se quedan dentro.",
  'rg_c2t'=>"Durante la inmersión", 'rg_c2a'=>"Ni fotos ni vídeos (para preservar el misterio y los enigmas).", 'rg_c2b'=>"Permaneced en grupo: separarse hace perder un tiempo valioso.", 'rg_c2c'=>"Manipulad los decorados con cuidado, no forcéis nunca un mecanismo.", 'rg_c2d'=>"Se puede pedir una <strong>pista</strong> en cualquier momento con el walkie facilitado.",
  'rg_c3t'=>"Seguridad", 'rg_c3a'=>"La palabra « <strong>LUZ</strong> » termina la partida al instante.", 'rg_c3b'=>"Salidas de emergencia señalizadas y accesibles en todo momento.", 'rg_c3c'=>"Un actor-máster del juego os vigila discretamente todo el rato.", 'rg_c3d'=>"Prohibido a personas bajo los efectos del alcohol o estupefacientes.",
  'rg_c4t'=>"La puntuación", 'rg_c4a'=>"El objetivo: <strong>« salir de las Backrooms »</strong> antes de que se acabe el tiempo.", 'rg_c4b'=>"Puntos extra recompensan los enigmas resueltos sin pista.", 'rg_c4c'=>"Tu tiempo de salida y tu puntuación aparecen en tu espacio privado.", 'rg_c4d'=>"Los mejores equipos entran en la clasificación pública.",
  'rg_cta'=>"¿Listo para intentar la experiencia?",
  'ct_title'=>"CONTÁCTANOS", 'ct_sub'=>"¿Una pregunta sobre la experiencia? Escríbenos, respondemos rápido.",
  'ct_nom'=>"Tu nombre *", 'ct_email'=>"Tu correo *", 'ct_sujet'=>"Asunto *", 'ct_msg'=>"Mensaje *", 'ct_send'=>"Enviar el mensaje",
  'ct_iadr'=>"Dirección", 'ct_itel'=>"Teléfono", 'ct_ihor'=>"Horario", 'ct_ires'=>"Redes sociales",
 ],
];
foreach ($__pages as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Page Infos pratiques ---
$__ip = [
 'fr' => [
  'ip_sub'=>"Tout ce qu'il faut savoir avant de venir",
  'ql_loc'=>"Localisation", 'ql_contact'=>"Contact", 'ql_tarifs'=>"Tarifs", 'ql_heb'=>"Hébergement", 'ql_int'=>"Interdictions",
  'ip_loc_t'=>"LOCALISATION", 'ip_loc_sub'=>"Où se situe notre escape game ?", 'lbl_adresse'=>"Adresse", 'lbl_ville'=>"Ville", 'lbl_cp'=>"Code postal",
  'ip_ct_t'=>"CONTACT", 'ip_ct_sub'=>"Comment nous contacter ?", 'lbl_mail'=>"Adresse mail", 'lbl_tel'=>"Numéro de téléphone", 'lbl_res'=>"Réseaux sociaux",
  'ph_nom'=>"Nom *", 'ph_email'=>"Email *", 'ph_tel'=>"Téléphone", 'ph_msg'=>"Votre message *", 'btn_envoyer'=>"ENVOYER",
  'ip_tar_t'=>"TARIFS", 'ip_tar_sub'=>"Combien coûte une partie ? (4h+ de jeu, repas et nuit sur place inclus)",
  'th_part'=>"Participants", 'th_prix'=>"Prix / personne",
  'tar_r1'=>"2 personnes", 'tar_r2'=>"3 personnes", 'tar_r3'=>"4 personnes", 'tar_r4'=>"5 personnes", 'tar_r5'=>"6 personnes", 'tar_r6'=>"7 à 10 personnes",
  'tar_note'=>"Salle <strong>Hardcore</strong> (5h) : majoration de <strong>+10 €/personne</strong>.<br>Aucun tarif étudiant.",
  'calc_titre'=>"Estimez votre tarif", 'calc_salle'=>"Salle", 'calc_o1'=>"Salle 1 — Facile", 'calc_o2'=>"Salle 2 — Standard", 'calc_o3'=>"Salle 3 — Hardcore (+10 €/pers)",
  'calc_nb'=>"Nombre de participants (2 à 10)", 'calc_err'=>"Indiquez de 2 à 10 participants.", 'calc_unit'=>" € / personne", 'calc_total'=>"Total : ",
  'ip_heb_t'=>"HÉBERGEMENT & RESTAURATION", 'ip_heb_sub'=>"L'immersion continue toute la nuit",
  'heb1_t'=>"La chambre", 'heb1_d'=>"Chambre double (lit séparable), volontairement nue : ni télé, ni table, ni mobilier superflu — 10 m² maximum, pour rester fidèle à l'ambiance liminale.",
  'heb2_t'=>"La restauration", 'heb2_d'=>"Rations de survie thématiques et la fameuse boisson « Eau d'Amande », tout droit sorties du lore des Backrooms.",
  'heb3_t'=>"Le petit-déjeuner", 'heb3_d'=>"<strong>Offert</strong> si votre équipe s'échappe ! En cas d'échec, il vous sera facturé <strong>6 €</strong>… une motivation de plus pour sortir.",
  'ip_int_t'=>"INTERDICTIONS", 'ip_int_sub'=>"Pour la sécurité et le bon déroulement de la partie, ces objets sont interdits :",
  'int1'=>"Téléphone portable", 'int2'=>"Nourriture", 'int3'=>"Arme à feu", 'int4'=>"Cigarette", 'int5'=>"Bombe", 'int6'=>"Arme blanche", 'int7'=>"Animaux", 'int8'=>"Parapluie",
 ],
 'en' => [
  'ip_sub'=>"Everything you need to know before coming",
  'ql_loc'=>"Location", 'ql_contact'=>"Contact", 'ql_tarifs'=>"Prices", 'ql_heb'=>"Accommodation", 'ql_int'=>"Prohibited items",
  'ip_loc_t'=>"LOCATION", 'ip_loc_sub'=>"Where is our escape game?", 'lbl_adresse'=>"Address", 'lbl_ville'=>"City", 'lbl_cp'=>"Postcode",
  'ip_ct_t'=>"CONTACT", 'ip_ct_sub'=>"How to reach us?", 'lbl_mail'=>"Email address", 'lbl_tel'=>"Phone number", 'lbl_res'=>"Social media",
  'ph_nom'=>"Name *", 'ph_email'=>"Email *", 'ph_tel'=>"Phone", 'ph_msg'=>"Your message *", 'btn_envoyer'=>"SEND",
  'ip_tar_t'=>"PRICES", 'ip_tar_sub'=>"How much is a game? (4h+ of play, meal and overnight stay included)",
  'th_part'=>"Participants", 'th_prix'=>"Price / person",
  'tar_r1'=>"2 people", 'tar_r2'=>"3 people", 'tar_r3'=>"4 people", 'tar_r4'=>"5 people", 'tar_r5'=>"6 people", 'tar_r6'=>"7 to 10 people",
  'tar_note'=>"<strong>Hardcore</strong> room (5h): surcharge of <strong>+€10/person</strong>.<br>No student rate.",
  'calc_titre'=>"Estimate your price", 'calc_salle'=>"Room", 'calc_o1'=>"Room 1 — Easy", 'calc_o2'=>"Room 2 — Standard", 'calc_o3'=>"Room 3 — Hardcore (+€10/person)",
  'calc_nb'=>"Number of participants (2 to 10)", 'calc_err'=>"Enter 2 to 10 participants.", 'calc_unit'=>" € / person", 'calc_total'=>"Total: ",
  'ip_heb_t'=>"ACCOMMODATION & FOOD", 'ip_heb_sub'=>"The immersion continues all night",
  'heb1_t'=>"The room", 'heb1_d'=>"Double room (separable bed), deliberately bare: no TV, no table, no superfluous furniture — 10 m² max, to stay true to the liminal mood.",
  'heb2_t'=>"The food", 'heb2_d'=>"Themed survival rations and the famous « Almond Water » drink, straight out of the Backrooms lore.",
  'heb3_t'=>"Breakfast", 'heb3_d'=>"<strong>Free</strong> if your team escapes! If you fail, it will cost you <strong>€6</strong>… one more reason to get out.",
  'ip_int_t'=>"PROHIBITED ITEMS", 'ip_int_sub'=>"For safety and a smooth game, these items are not allowed:",
  'int1'=>"Mobile phone", 'int2'=>"Food", 'int3'=>"Firearm", 'int4'=>"Cigarette", 'int5'=>"Spray can", 'int6'=>"Blade", 'int7'=>"Pets", 'int8'=>"Umbrella",
 ],
 'es' => [
  'ip_sub'=>"Todo lo que hay que saber antes de venir",
  'ql_loc'=>"Ubicación", 'ql_contact'=>"Contacto", 'ql_tarifs'=>"Tarifas", 'ql_heb'=>"Alojamiento", 'ql_int'=>"Prohibiciones",
  'ip_loc_t'=>"UBICACIÓN", 'ip_loc_sub'=>"¿Dónde está nuestro escape game?", 'lbl_adresse'=>"Dirección", 'lbl_ville'=>"Ciudad", 'lbl_cp'=>"Código postal",
  'ip_ct_t'=>"CONTACTO", 'ip_ct_sub'=>"¿Cómo contactarnos?", 'lbl_mail'=>"Correo electrónico", 'lbl_tel'=>"Número de teléfono", 'lbl_res'=>"Redes sociales",
  'ph_nom'=>"Nombre *", 'ph_email'=>"Correo *", 'ph_tel'=>"Teléfono", 'ph_msg'=>"Tu mensaje *", 'btn_envoyer'=>"ENVIAR",
  'ip_tar_t'=>"TARIFAS", 'ip_tar_sub'=>"¿Cuánto cuesta una partida? (4h+ de juego, comida y noche incluidas)",
  'th_part'=>"Participantes", 'th_prix'=>"Precio / persona",
  'tar_r1'=>"2 personas", 'tar_r2'=>"3 personas", 'tar_r3'=>"4 personas", 'tar_r4'=>"5 personas", 'tar_r5'=>"6 personas", 'tar_r6'=>"7 a 10 personas",
  'tar_note'=>"Sala <strong>Hardcore</strong> (5h): recargo de <strong>+10 €/persona</strong>.<br>Sin tarifa de estudiante.",
  'calc_titre'=>"Calcula tu tarifa", 'calc_salle'=>"Sala", 'calc_o1'=>"Sala 1 — Fácil", 'calc_o2'=>"Sala 2 — Estándar", 'calc_o3'=>"Sala 3 — Hardcore (+10 €/pers)",
  'calc_nb'=>"Número de participantes (2 a 10)", 'calc_err'=>"Indica de 2 a 10 participantes.", 'calc_unit'=>" € / persona", 'calc_total'=>"Total: ",
  'ip_heb_t'=>"ALOJAMIENTO Y COMIDA", 'ip_heb_sub'=>"La inmersión continúa toda la noche",
  'heb1_t'=>"La habitación", 'heb1_d'=>"Habitación doble (cama separable), deliberadamente desnuda: ni tele, ni mesa, ni mobiliario superfluo — 10 m² máximo, para ser fiel al ambiente liminal.",
  'heb2_t'=>"La comida", 'heb2_d'=>"Raciones de supervivencia temáticas y la famosa bebida « Agua de Almendra », salidas del lore de las Backrooms.",
  'heb3_t'=>"El desayuno", 'heb3_d'=>"<strong>Gratis</strong> si tu equipo escapa. Si fallas, se te cobrará <strong>6 €</strong>… una motivación más para salir.",
  'ip_int_t'=>"PROHIBICIONES", 'ip_int_sub'=>"Por seguridad y para el buen desarrollo de la partida, estos objetos están prohibidos:",
  'int1'=>"Teléfono móvil", 'int2'=>"Comida", 'int3'=>"Arma de fuego", 'int4'=>"Cigarrillo", 'int5'=>"Aerosol", 'int6'=>"Arma blanca", 'int7'=>"Animales", 'int8'=>"Paraguas",
 ],
];
foreach ($__ip as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Classement + comptes + profil (avis / mot de passe) ---
$__cpt = [
 'fr' => [
  'cl_title'=>"CLASSEMENT", 'cl_sub'=>"Les équipes qui ont survécu aux Backrooms… ou presque.",
  'cl_empty'=>"Aucune partie jouée pour le moment. Le classement apparaîtra après les premières sessions !",
  'cl_equipe'=>"Équipe", 'cl_points'=>"Points", 'cl_temps'=>"Meilleur temps", 'cl_parties'=>"Parties", 'cl_sorties'=>"Sorties",
  'cl_cta'=>"Votre équipe peut faire mieux ?", 'cl_cta_btn'=>"DÉFIER LES BACKROOMS",
  'lg_co_title'=>"Connexion", 'lg_email'=>"Email", 'lg_pass'=>"Mot de passe", 'lg_co_btn'=>"Se connecter",
  'lg_no_acct'=>"Pas encore de compte ?", 'lg_create'=>"Créez-en un", 'lg_forgot'=>"Mot de passe oublié ?",
  'lg_in_title'=>"Inscription", 'lg_nom'=>"Nom *", 'lg_prenom'=>"Prénom *", 'lg_pseudo'=>"Pseudo *", 'lg_email_r'=>"Email *", 'lg_tel'=>"Téléphone", 'lg_pass_r'=>"Mot de passe *", 'lg_in_btn'=>"S'inscrire", 'lg_already'=>"Déjà inscrit ?", 'lg_login_link'=>"Connectez-vous",
  'lg_fg_title'=>"Mot de passe oublié", 'lg_fg_txt'=>"Saisissez votre adresse email : nous vous enverrons un lien pour choisir un nouveau mot de passe.", 'lg_fg_btn'=>"Envoyer le lien", 'lg_back_login'=>"‹ Retour à la connexion",
  'lg_rs_title'=>"Nouveau mot de passe", 'lg_rs_new'=>"Nouveau mot de passe (6 caractères min.)", 'lg_rs_confirm'=>"Confirmez le mot de passe", 'lg_rs_btn'=>"Changer le mot de passe", 'lg_redo'=>"Refaire une demande", 'lg_rs_login'=>"Se connecter",
  'pr_title'=>"Mon Profil", 'pr_tab_infos'=>"Informations personnelles", 'pr_tab_pass'=>"Mot de passe", 'pr_tab_avis'=>"Laisser un avis", 'pr_logout'=>"Déconnexion",
  'av_intro'=>"Avez-vous réussi à sortir des Backrooms ? Laissez-nous votre avis sur l'expérience !", 'av_note'=>"Note (sur 5) *",
  'av_o5'=>"5 - Excellent, inoubliable !", 'av_o4'=>"4 - Très bien, angoissant", 'av_o3'=>"3 - Bien, mais peut mieux faire", 'av_o2'=>"2 - Décevant", 'av_o1'=>"1 - Très mauvais",
  'av_txt'=>"Votre commentaire *", 'av_btn'=>"Envoyer mon avis",
  'pw_actuel'=>"Mot de passe actuel *", 'pw_nouveau'=>"Nouveau mot de passe *", 'pw_confirm'=>"Confirmer le nouveau mot de passe *", 'pw_btn'=>"Modifier le mot de passe",
 ],
 'en' => [
  'cl_title'=>"LEADERBOARD", 'cl_sub'=>"The teams that survived the Backrooms… or almost.",
  'cl_empty'=>"No game played yet. The leaderboard will appear after the first sessions!",
  'cl_equipe'=>"Team", 'cl_points'=>"Points", 'cl_temps'=>"Best time", 'cl_parties'=>"Games", 'cl_sorties'=>"Escapes",
  'cl_cta'=>"Can your team do better?", 'cl_cta_btn'=>"CHALLENGE THE BACKROOMS",
  'lg_co_title'=>"Log in", 'lg_email'=>"Email", 'lg_pass'=>"Password", 'lg_co_btn'=>"Log in",
  'lg_no_acct'=>"No account yet?", 'lg_create'=>"Create one", 'lg_forgot'=>"Forgot password?",
  'lg_in_title'=>"Sign up", 'lg_nom'=>"Last name *", 'lg_prenom'=>"First name *", 'lg_pseudo'=>"Username *", 'lg_email_r'=>"Email *", 'lg_tel'=>"Phone", 'lg_pass_r'=>"Password *", 'lg_in_btn'=>"Sign up", 'lg_already'=>"Already registered?", 'lg_login_link'=>"Log in",
  'lg_fg_title'=>"Forgot password", 'lg_fg_txt'=>"Enter your email address: we'll send you a link to choose a new password.", 'lg_fg_btn'=>"Send the link", 'lg_back_login'=>"‹ Back to login",
  'lg_rs_title'=>"New password", 'lg_rs_new'=>"New password (6 characters min.)", 'lg_rs_confirm'=>"Confirm the password", 'lg_rs_btn'=>"Change password", 'lg_redo'=>"Request again", 'lg_rs_login'=>"Log in",
  'pr_title'=>"My Profile", 'pr_tab_infos'=>"Personal information", 'pr_tab_pass'=>"Password", 'pr_tab_avis'=>"Leave a review", 'pr_logout'=>"Log out",
  'av_intro'=>"Did you manage to escape the Backrooms? Leave us your review of the experience!", 'av_note'=>"Rating (out of 5) *",
  'av_o5'=>"5 - Excellent, unforgettable!", 'av_o4'=>"4 - Very good, scary", 'av_o3'=>"3 - Good, but could be better", 'av_o2'=>"2 - Disappointing", 'av_o1'=>"1 - Very bad",
  'av_txt'=>"Your comment *", 'av_btn'=>"Send my review",
  'pw_actuel'=>"Current password *", 'pw_nouveau'=>"New password *", 'pw_confirm'=>"Confirm the new password *", 'pw_btn'=>"Change password",
 ],
 'es' => [
  'cl_title'=>"CLASIFICACIÓN", 'cl_sub'=>"Los equipos que sobrevivieron a las Backrooms… o casi.",
  'cl_empty'=>"Aún no se ha jugado ninguna partida. ¡La clasificación aparecerá tras las primeras sesiones!",
  'cl_equipe'=>"Equipo", 'cl_points'=>"Puntos", 'cl_temps'=>"Mejor tiempo", 'cl_parties'=>"Partidas", 'cl_sorties'=>"Salidas",
  'cl_cta'=>"¿Tu equipo puede hacerlo mejor?", 'cl_cta_btn'=>"DESAFÍA LAS BACKROOMS",
  'lg_co_title'=>"Iniciar sesión", 'lg_email'=>"Correo", 'lg_pass'=>"Contraseña", 'lg_co_btn'=>"Iniciar sesión",
  'lg_no_acct'=>"¿Aún no tienes cuenta?", 'lg_create'=>"Crea una", 'lg_forgot'=>"¿Olvidaste tu contraseña?",
  'lg_in_title'=>"Registro", 'lg_nom'=>"Apellido *", 'lg_prenom'=>"Nombre *", 'lg_pseudo'=>"Usuario *", 'lg_email_r'=>"Correo *", 'lg_tel'=>"Teléfono", 'lg_pass_r'=>"Contraseña *", 'lg_in_btn'=>"Registrarse", 'lg_already'=>"¿Ya registrado?", 'lg_login_link'=>"Inicia sesión",
  'lg_fg_title'=>"Contraseña olvidada", 'lg_fg_txt'=>"Introduce tu correo: te enviaremos un enlace para elegir una nueva contraseña.", 'lg_fg_btn'=>"Enviar el enlace", 'lg_back_login'=>"‹ Volver al inicio de sesión",
  'lg_rs_title'=>"Nueva contraseña", 'lg_rs_new'=>"Nueva contraseña (mín. 6 caracteres)", 'lg_rs_confirm'=>"Confirma la contraseña", 'lg_rs_btn'=>"Cambiar la contraseña", 'lg_redo'=>"Volver a solicitar", 'lg_rs_login'=>"Iniciar sesión",
  'pr_title'=>"Mi Perfil", 'pr_tab_infos'=>"Información personal", 'pr_tab_pass'=>"Contraseña", 'pr_tab_avis'=>"Dejar una reseña", 'pr_logout'=>"Cerrar sesión",
  'av_intro'=>"¿Conseguiste salir de las Backrooms? ¡Déjanos tu reseña de la experiencia!", 'av_note'=>"Nota (sobre 5) *",
  'av_o5'=>"5 - ¡Excelente, inolvidable!", 'av_o4'=>"4 - Muy bien, angustiante", 'av_o3'=>"3 - Bien, pero mejorable", 'av_o2'=>"2 - Decepcionante", 'av_o1'=>"1 - Muy malo",
  'av_txt'=>"Tu comentario *", 'av_btn'=>"Enviar mi reseña",
  'pw_actuel'=>"Contraseña actual *", 'pw_nouveau'=>"Nueva contraseña *", 'pw_confirm'=>"Confirmar la nueva contraseña *", 'pw_btn'=>"Cambiar la contraseña",
 ],
];
foreach ($__cpt as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Page Réservation ---
$__rv = [
 'fr' => [
  'rv_ins_t'=>"INSCRIPTION", 'rv_ins_sub'=>"Nous avons besoin de vos informations !", 'rv_already'=>"Déjà un compte ?", 'rv_login'=>"Connectez-vous",
  'ph_NOM'=>"NOM", 'ph_PRENOM'=>"PRÉNOM", 'ph_EMAIL'=>"EMAIL", 'ph_TEL'=>"TÉLÉPHONE", 'ph_EQUIPE'=>"NOM DE L'ÉQUIPE", 'ph_CODE'=>"OU CODE D'INVITATION (rejoindre une équipe)", 'ph_NB'=>"NOMBRE DE PARTICIPANTS (2 à 10)",
  'rv_salle_ph'=>"CHOISIR UNE SALLE…", 'rv_s1'=>"Salle 1 — Le Niveau 0 (facile, dès 10 ans)", 'rv_s2'=>"Salle 2 — Les Couloirs jaunes (standard, dès 14 ans)", 'rv_s3'=>"Salle 3 — Le Niveau ! (hardcore, dès 16 ans)",
  'rv_dob'=>"Date de naissance", 'rv_jour'=>"Jour", 'rv_mois'=>"Mois", 'rv_annee'=>"Année",
  'rv_dispo_t'=>"NOS DISPONIBILITÉS", 'rv_come'=>"Venez jouer avec nous en ", 'cal_dispo'=>"Disponible", 'cal_complet'=>"Complet", 'cal_ferme'=>"Fermé",
  'rv_prev'=>"‹ Mois précédent", 'rv_next'=>"Passer au mois suivant ›",
  'rv_sante_t'=>"SANTÉ ET SÉCURITÉ", 'rv_sante_sub'=>"Votre santé et votre sécurité sont notre priorité !",
  'rv_q1'=>"Avez-vous des problèmes cardiaques ?", 'rv_q2'=>"Souffrez-vous d'épilepsie ou de sensibilité aux lumières stroboscopiques ?", 'rv_q3'=>"Avez-vous des difficultés respiratoires ou de l'asthme ?", 'rv_q4'=>"Souffrez-vous de claustrophobie ?",
  'rv_oui'=>"OUI", 'rv_non'=>"NON", 'rv_regime_q'=>"Avez-vous un régime alimentaire particulier ? (un repas est servi)",
  'reg_aucun'=>"Aucun", 'reg_vegetarien'=>"Végétarien", 'reg_vegan'=>"Végan", 'reg_sans_gluten'=>"Sans gluten", 'reg_halal'=>"Halal", 'reg_autre'=>"Autre",
  'rv_pay_t'=>"PAIEMENT", 'rv_pay_sub'=>"Plus qu'une étape avant de plonger dans les Backrooms !",
  'rv_pay_card'=>"Je paye par carte dès maintenant", 'rv_pay_btn'=>"PAYER", 'rv_pay_place'=>"Je souhaite payer sur place", 'rv_pay_info'=>"Réglez votre session directement à l'accueil le soir de l'événement.", 'rv_pay_finalise'=>"JE FINALISE",
  'rv_myresa_t'=>"MES RÉSERVATIONS", 'th_salle'=>"Salle", 'th_date'=>"Date", 'th_joueurs'=>"Joueurs", 'th_statut'=>"Statut",
  'rv_js_pre'=>"Tarif estimé : ", 'rv_js_suf'=>" €/pers, repas et nuit inclus)",
 ],
 'en' => [
  'rv_ins_t'=>"SIGN UP", 'rv_ins_sub'=>"We need your details!", 'rv_already'=>"Already have an account?", 'rv_login'=>"Log in",
  'ph_NOM'=>"LAST NAME", 'ph_PRENOM'=>"FIRST NAME", 'ph_EMAIL'=>"EMAIL", 'ph_TEL'=>"PHONE", 'ph_EQUIPE'=>"TEAM NAME", 'ph_CODE'=>"OR INVITE CODE (join a team)", 'ph_NB'=>"NUMBER OF PARTICIPANTS (2 to 10)",
  'rv_salle_ph'=>"CHOOSE A ROOM…", 'rv_s1'=>"Room 1 — Level 0 (easy, ages 10+)", 'rv_s2'=>"Room 2 — The Yellow Corridors (standard, ages 14+)", 'rv_s3'=>"Room 3 — Level ! (hardcore, ages 16+)",
  'rv_dob'=>"Date of birth", 'rv_jour'=>"Day", 'rv_mois'=>"Month", 'rv_annee'=>"Year",
  'rv_dispo_t'=>"OUR AVAILABILITY", 'rv_come'=>"Come play with us in ", 'cal_dispo'=>"Available", 'cal_complet'=>"Full", 'cal_ferme'=>"Closed",
  'rv_prev'=>"‹ Previous month", 'rv_next'=>"Next month ›",
  'rv_sante_t'=>"HEALTH & SAFETY", 'rv_sante_sub'=>"Your health and safety are our priority!",
  'rv_q1'=>"Do you have any heart problems?", 'rv_q2'=>"Do you have epilepsy or sensitivity to strobe lights?", 'rv_q3'=>"Do you have breathing difficulties or asthma?", 'rv_q4'=>"Do you suffer from claustrophobia?",
  'rv_oui'=>"YES", 'rv_non'=>"NO", 'rv_regime_q'=>"Do you have any special diet? (a meal is served)",
  'reg_aucun'=>"None", 'reg_vegetarien'=>"Vegetarian", 'reg_vegan'=>"Vegan", 'reg_sans_gluten'=>"Gluten-free", 'reg_halal'=>"Halal", 'reg_autre'=>"Other",
  'rv_pay_t'=>"PAYMENT", 'rv_pay_sub'=>"One more step before diving into the Backrooms!",
  'rv_pay_card'=>"I pay by card now", 'rv_pay_btn'=>"PAY", 'rv_pay_place'=>"I'd rather pay on site", 'rv_pay_info'=>"Pay for your session directly at the front desk on the evening of the event.", 'rv_pay_finalise'=>"FINALISE",
  'rv_myresa_t'=>"MY BOOKINGS", 'th_salle'=>"Room", 'th_date'=>"Date", 'th_joueurs'=>"Players", 'th_statut'=>"Status",
  'rv_js_pre'=>"Estimated price: ", 'rv_js_suf'=>" €/person, meal and overnight stay included)",
 ],
 'es' => [
  'rv_ins_t'=>"REGISTRO", 'rv_ins_sub'=>"¡Necesitamos tus datos!", 'rv_already'=>"¿Ya tienes cuenta?", 'rv_login'=>"Inicia sesión",
  'ph_NOM'=>"APELLIDO", 'ph_PRENOM'=>"NOMBRE", 'ph_EMAIL'=>"CORREO", 'ph_TEL'=>"TELÉFONO", 'ph_EQUIPE'=>"NOMBRE DEL EQUIPO", 'ph_CODE'=>"O CÓDIGO DE INVITACIÓN (unirse a un equipo)", 'ph_NB'=>"NÚMERO DE PARTICIPANTES (2 a 10)",
  'rv_salle_ph'=>"ELIGE UNA SALA…", 'rv_s1'=>"Sala 1 — El Nivel 0 (fácil, desde 10 años)", 'rv_s2'=>"Sala 2 — Los Pasillos Amarillos (estándar, desde 14 años)", 'rv_s3'=>"Sala 3 — ¡El Nivel ! (hardcore, desde 16 años)",
  'rv_dob'=>"Fecha de nacimiento", 'rv_jour'=>"Día", 'rv_mois'=>"Mes", 'rv_annee'=>"Año",
  'rv_dispo_t'=>"NUESTRA DISPONIBILIDAD", 'rv_come'=>"Ven a jugar con nosotros en ", 'cal_dispo'=>"Disponible", 'cal_complet'=>"Completo", 'cal_ferme'=>"Cerrado",
  'rv_prev'=>"‹ Mes anterior", 'rv_next'=>"Mes siguiente ›",
  'rv_sante_t'=>"SALUD Y SEGURIDAD", 'rv_sante_sub'=>"¡Tu salud y tu seguridad son nuestra prioridad!",
  'rv_q1'=>"¿Tienes problemas cardíacos?", 'rv_q2'=>"¿Sufres epilepsia o sensibilidad a las luces estroboscópicas?", 'rv_q3'=>"¿Tienes dificultades respiratorias o asma?", 'rv_q4'=>"¿Sufres claustrofobia?",
  'rv_oui'=>"SÍ", 'rv_non'=>"NO", 'rv_regime_q'=>"¿Tienes alguna dieta especial? (se sirve una comida)",
  'reg_aucun'=>"Ninguna", 'reg_vegetarien'=>"Vegetariano", 'reg_vegan'=>"Vegano", 'reg_sans_gluten'=>"Sin gluten", 'reg_halal'=>"Halal", 'reg_autre'=>"Otra",
  'rv_pay_t'=>"PAGO", 'rv_pay_sub'=>"¡Un paso más antes de sumergirte en las Backrooms!",
  'rv_pay_card'=>"Pago con tarjeta ahora", 'rv_pay_btn'=>"PAGAR", 'rv_pay_place'=>"Prefiero pagar en el sitio", 'rv_pay_info'=>"Paga tu sesión directamente en recepción la noche del evento.", 'rv_pay_finalise'=>"FINALIZAR",
  'rv_myresa_t'=>"MIS RESERVAS", 'th_salle'=>"Sala", 'th_date'=>"Fecha", 'th_joueurs'=>"Jugadores", 'th_statut'=>"Estado",
  'rv_js_pre'=>"Precio estimado: ", 'rv_js_suf'=>" €/persona, comida y noche incluidas)",
 ],
];
foreach ($__rv as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Page Profil (espace privé) ---
$__pf = [
 'fr' => [
  'pf_title'=>"MON PROFIL", 'pf_sub'=>"Gérez vos informations et vos réservations !",
  'pf_mdp_auto'=>"⚠️ Votre compte a été créé automatiquement lors de votre réservation : <strong>définissez un mot de passe ci-dessous</strong> pour pouvoir vous reconnecter plus tard.",
  'pf_pseudo'=>"Pseudo", 'pf_email'=>"Email", 'pf_tel'=>"Téléphone", 'pf_mdp'=>"Mot de passe", 'pf_mdp_ph'=>"Laisser vide pour ne pas changer", 'pf_photo'=>"Changer la photo", 'pf_save'=>"Modifier mes informations",
  'pf_eq_t'=>"MON ÉQUIPE", 'pf_eq_sub'=>"Gérez votre équipe", 'pf_no_eq'=>"Vous n'avez pas encore d'équipe.", 'pf_create_eq'=>"Créer mon équipe",
  'pf_eq_nom'=>"Nom de l'équipe", 'pf_eq_nb'=>"Nombre de membres", 'pf_eq_niv'=>"Niveau max atteint", 'pf_eq_code'=>"Code d'invitation", 'pf_eq_gerer'=>"Gérer mon équipe",
  'pf_stats_t'=>"MES STATISTIQUES", 'pf_stats_sub'=>"Voici vos statistiques durant vos parties !",
  'pf_st_temps'=>"Temps moyen pour s'échapper", 'pf_st_salles'=>"Salles explorées", 'pf_st_taux'=>"Taux de réussite", 'pf_st_pts'=>"Mes points",
  'pf_part_titre'=>"Fier·e de votre score ? Partagez votre exploit&nbsp;:", 'pf_part_msg'=>"J'ai bravé les BACKROOMS avec l'équipe %s : %d points ! Oserez-vous nous suivre dans les couloirs ?",
  'pf_parties_t'=>"MES PARTIES", 'pf_parties_sub'=>"Rappelez-vous de vos parties avec nous !",
  'pf_no_parties'=>"Aucune partie pour le moment.", 'pf_resa_first'=>"Réservez votre première session ›",
  'pf_th_session'=>"Session", 'pf_th_date'=>"Date", 'pf_th_heure'=>"Heure",
  'pf_st_annulee'=>"Annulée", 'pf_st_terminee'=>"Terminée", 'pf_st_avenir'=>"À venir",
  'pf_annuler'=>"Annuler", 'pf_confirm_annul'=>"Annuler cette réservation ?", 'pf_leave_avis'=>"Laisser un avis sur votre expérience ›",
  'pf_zone_t'=>"ZONE SÉCURITÉ", 'pf_zone_sub'=>"La sécurité de vos données est notre priorité.",
  'pf_chg_mdp'=>"Changer le mot de passe", 'pf_chg_mdp_d'=>"Sécurisez votre compte en modifiant votre mot de passe.", 'pf_deco'=>"Déconnexion", 'pf_deco_d'=>"Se déconnecter de votre compte.",
 ],
 'en' => [
  'pf_title'=>"MY PROFILE", 'pf_sub'=>"Manage your details and your bookings!",
  'pf_mdp_auto'=>"⚠️ Your account was created automatically during your booking: <strong>set a password below</strong> so you can log back in later.",
  'pf_pseudo'=>"Username", 'pf_email'=>"Email", 'pf_tel'=>"Phone", 'pf_mdp'=>"Password", 'pf_mdp_ph'=>"Leave empty to keep it", 'pf_photo'=>"Change photo", 'pf_save'=>"Save my information",
  'pf_eq_t'=>"MY TEAM", 'pf_eq_sub'=>"Manage your team", 'pf_no_eq'=>"You don't have a team yet.", 'pf_create_eq'=>"Create my team",
  'pf_eq_nom'=>"Team name", 'pf_eq_nb'=>"Number of members", 'pf_eq_niv'=>"Highest level reached", 'pf_eq_code'=>"Invite code", 'pf_eq_gerer'=>"Manage my team",
  'pf_stats_t'=>"MY STATISTICS", 'pf_stats_sub'=>"Here are your stats across your games!",
  'pf_st_temps'=>"Average escape time", 'pf_st_salles'=>"Rooms explored", 'pf_st_taux'=>"Success rate", 'pf_st_pts'=>"My points",
  'pf_part_titre'=>"Proud of your score? Share your feat&nbsp;:", 'pf_part_msg'=>"I braved the BACKROOMS with team %s: %d points! Dare to follow us into the corridors?",
  'pf_parties_t'=>"MY GAMES", 'pf_parties_sub'=>"Remember your games with us!",
  'pf_no_parties'=>"No game yet.", 'pf_resa_first'=>"Book your first session ›",
  'pf_th_session'=>"Session", 'pf_th_date'=>"Date", 'pf_th_heure'=>"Time",
  'pf_st_annulee'=>"Cancelled", 'pf_st_terminee'=>"Finished", 'pf_st_avenir'=>"Upcoming",
  'pf_annuler'=>"Cancel", 'pf_confirm_annul'=>"Cancel this booking?", 'pf_leave_avis'=>"Leave a review of your experience ›",
  'pf_zone_t'=>"SECURITY ZONE", 'pf_zone_sub'=>"The security of your data is our priority.",
  'pf_chg_mdp'=>"Change password", 'pf_chg_mdp_d'=>"Secure your account by changing your password.", 'pf_deco'=>"Log out", 'pf_deco_d'=>"Log out of your account.",
 ],
 'es' => [
  'pf_title'=>"MI PERFIL", 'pf_sub'=>"¡Gestiona tus datos y tus reservas!",
  'pf_mdp_auto'=>"⚠️ Tu cuenta se creó automáticamente durante tu reserva: <strong>define una contraseña abajo</strong> para poder volver a entrar más tarde.",
  'pf_pseudo'=>"Usuario", 'pf_email'=>"Correo", 'pf_tel'=>"Teléfono", 'pf_mdp'=>"Contraseña", 'pf_mdp_ph'=>"Déjalo vacío para no cambiarla", 'pf_photo'=>"Cambiar la foto", 'pf_save'=>"Guardar mi información",
  'pf_eq_t'=>"MI EQUIPO", 'pf_eq_sub'=>"Gestiona tu equipo", 'pf_no_eq'=>"Aún no tienes equipo.", 'pf_create_eq'=>"Crear mi equipo",
  'pf_eq_nom'=>"Nombre del equipo", 'pf_eq_nb'=>"Número de miembros", 'pf_eq_niv'=>"Nivel máximo alcanzado", 'pf_eq_code'=>"Código de invitación", 'pf_eq_gerer'=>"Gestionar mi equipo",
  'pf_stats_t'=>"MIS ESTADÍSTICAS", 'pf_stats_sub'=>"¡Aquí están tus estadísticas en tus partidas!",
  'pf_st_temps'=>"Tiempo medio para escapar", 'pf_st_salles'=>"Salas exploradas", 'pf_st_taux'=>"Tasa de éxito", 'pf_st_pts'=>"Mis puntos",
  'pf_part_titre'=>"¿Orgulloso de tu puntuación? Comparte tu hazaña&nbsp;:", 'pf_part_msg'=>"¡Desafié las BACKROOMS con el equipo %s: %d puntos! ¿Te atreves a seguirnos por los pasillos?",
  'pf_parties_t'=>"MIS PARTIDAS", 'pf_parties_sub'=>"¡Recuerda tus partidas con nosotros!",
  'pf_no_parties'=>"Aún no hay partidas.", 'pf_resa_first'=>"Reserva tu primera sesión ›",
  'pf_th_session'=>"Sesión", 'pf_th_date'=>"Fecha", 'pf_th_heure'=>"Hora",
  'pf_st_annulee'=>"Cancelada", 'pf_st_terminee'=>"Terminada", 'pf_st_avenir'=>"Próxima",
  'pf_annuler'=>"Cancelar", 'pf_confirm_annul'=>"¿Cancelar esta reserva?", 'pf_leave_avis'=>"Deja una reseña de tu experiencia ›",
  'pf_zone_t'=>"ZONA DE SEGURIDAD", 'pf_zone_sub'=>"La seguridad de tus datos es nuestra prioridad.",
  'pf_chg_mdp'=>"Cambiar la contraseña", 'pf_chg_mdp_d'=>"Protege tu cuenta cambiando tu contraseña.", 'pf_deco'=>"Cerrar sesión", 'pf_deco_d'=>"Cerrar la sesión de tu cuenta.",
 ],
];
foreach ($__pf as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

// --- Page Mentions légales ---
$__mn = [
 'fr' => [
  'mn_title'=>"MENTIONS LÉGALES", 'mn_id_t'=>"Identification de l'entreprise :", 'mn_id_edit'=>"Le site %s est édité par :",
  'mn_l_raison'=>"Raison sociale :", 'mn_forme_v'=>"Projet pédagogique étudiant (BUT MMI — IUT de Troyes)", 'mn_l_forme'=>"Forme juridique :", 'mn_l_adr'=>"Adresse :", 'mn_l_email'=>"Email :", 'mn_l_tel'=>"Téléphone :",
  'mn_cookies_t'=>"Cookies :", 'mn_cookies_p'=>"Ce site est susceptible d'utiliser des cookies techniques nécessaires à son bon fonctionnement, ainsi que des cookies analytiques pour mesurer l'audience. Vous pouvez à tout moment paramétrer ou refuser les cookies depuis les réglages de votre navigateur.",
  'mn_pi_t'=>"Propriété intellectuelle", 'mn_pi_p'=>"L'ensemble des contenus présents sur ce site (textes, images, illustrations, logo, nom « Backrooms ») sont la propriété exclusive de Backrooms Escape Game et sont protégés par le droit français de la propriété intellectuelle. Toute reproduction non autorisée est interdite.",
  'mn_host_t'=>"Hébergeur :", 'mn_host_intro'=>"Ce site est hébergé par :", 'mn_host_v'=>"Serveur pédagogique de l'IUT de Troyes<br><strong>Adresse :</strong> 9 rue de Québec, 10000 Troyes<br><strong>Site :</strong> mmi25c02.mmi-troyes.fr",
  'mn_rgpd_t'=>"Données personnelles — RGPD", 'mn_rgpd_intro'=>"Conformément au RGPD et à la loi Informatique et Libertés, vous disposez de droits sur vos données personnelles.",
  'mn_collect_l'=>"Données collectées :", 'mn_collect_p'=>"Lors de votre inscription : nom, prénom, adresse email, numéro de téléphone, date de naissance et données de santé déclarées volontairement.",
  'mn_final_l'=>"Finalité de la collecte :", 'mn_final_p'=>"Ces données servent uniquement à gérer vos réservations, assurer votre sécurité lors de la session et vous envoyer une confirmation.",
  'mn_duree_l'=>"Durée de conservation :", 'mn_duree_p'=>"Vos données sont conservées 3 ans maximum après votre dernière réservation, puis supprimées.",
  'mn_vente_l'=>"Vente de données :", 'mn_vente_p'=>"Vos données ne sont jamais vendues, louées ou transmises à des tiers à des fins commerciales.",
  'mn_droits_l'=>"Vos droits :", 'mn_droits_intro'=>"Conformément au RGPD, vous disposez des droits suivants :",
  'mn_d1'=>"Droit d'accès à vos données", 'mn_d2'=>"Droit de rectification", 'mn_d3'=>"Droit à l'effacement (« droit à l'oubli »)", 'mn_d4'=>"Droit d'opposition au traitement", 'mn_d5'=>"Droit à la portabilité",
  'mn_exercer'=>"Pour exercer ces droits : backroomsescapegame@gmail.com. Vous pouvez aussi saisir la CNIL :",
  'mn_resp_t'=>"Limitation de responsabilité", 'mn_resp_p'=>"Backrooms Escape Game s'efforce de maintenir le site accessible et à jour, mais ne peut garantir l'absence d'interruptions ou d'erreurs. Notre responsabilité ne saurait être engagée en cas d'indisponibilité ou de dommages liés à l'utilisation du site.",
  'mn_droit_t'=>"Droit applicable", 'mn_droit_p'=>"Les présentes mentions légales sont soumises au droit français. En cas de litige, les tribunaux français seront seuls compétents.",
  'mn_credits_t'=>"Crédits", 'mn_credits_p'=>"Certaines illustrations d'ambiance proviennent de Wikimedia Commons (licences libres Creative Commons / domaine public). Les autres visuels, le logo et l'identité graphique sont la propriété de Lumina Studio.",
  'mn_maj'=>"Dernière mise à jour : juin 2026",
 ],
 'en' => [
  'mn_title'=>"LEGAL NOTICE", 'mn_id_t'=>"Company identification:", 'mn_id_edit'=>"The website %s is published by:",
  'mn_l_raison'=>"Company name:", 'mn_forme_v'=>"Student educational project (BUT MMI — IUT de Troyes)", 'mn_l_forme'=>"Legal form:", 'mn_l_adr'=>"Address:", 'mn_l_email'=>"Email:", 'mn_l_tel'=>"Phone:",
  'mn_cookies_t'=>"Cookies:", 'mn_cookies_p'=>"This site may use technical cookies required for its operation, as well as analytics cookies to measure audience. You can set or refuse cookies at any time in your browser settings.",
  'mn_pi_t'=>"Intellectual property", 'mn_pi_p'=>"All content on this site (texts, images, illustrations, logo, the name « Backrooms ») is the exclusive property of Backrooms Escape Game and is protected by French intellectual property law. Any unauthorised reproduction is prohibited.",
  'mn_host_t'=>"Host:", 'mn_host_intro'=>"This site is hosted by:", 'mn_host_v'=>"Educational server of IUT de Troyes<br><strong>Address:</strong> 9 rue de Québec, 10000 Troyes<br><strong>Site:</strong> mmi25c02.mmi-troyes.fr",
  'mn_rgpd_t'=>"Personal data — GDPR", 'mn_rgpd_intro'=>"In accordance with the GDPR and the French Data Protection Act, you have rights over your personal data.",
  'mn_collect_l'=>"Data collected:", 'mn_collect_p'=>"At sign-up: last name, first name, email address, phone number, date of birth and voluntarily declared health data.",
  'mn_final_l'=>"Purpose of collection:", 'mn_final_p'=>"This data is used only to manage your bookings, ensure your safety during the session and send you a confirmation.",
  'mn_duree_l'=>"Retention period:", 'mn_duree_p'=>"Your data is kept for a maximum of 3 years after your last booking, then deleted.",
  'mn_vente_l'=>"Data selling:", 'mn_vente_p'=>"Your data is never sold, rented or shared with third parties for commercial purposes.",
  'mn_droits_l'=>"Your rights:", 'mn_droits_intro'=>"Under the GDPR, you have the following rights:",
  'mn_d1'=>"Right of access to your data", 'mn_d2'=>"Right to rectification", 'mn_d3'=>"Right to erasure (« right to be forgotten »)", 'mn_d4'=>"Right to object to processing", 'mn_d5'=>"Right to data portability",
  'mn_exercer'=>"To exercise these rights: backroomsescapegame@gmail.com. You may also contact the French CNIL:",
  'mn_resp_t'=>"Limitation of liability", 'mn_resp_p'=>"Backrooms Escape Game strives to keep the site available and up to date, but cannot guarantee the absence of interruptions or errors. We cannot be held liable for unavailability or damage related to the use of the site.",
  'mn_droit_t'=>"Applicable law", 'mn_droit_p'=>"This legal notice is governed by French law. In the event of a dispute, the French courts shall have sole jurisdiction.",
  'mn_credits_t'=>"Credits", 'mn_credits_p'=>"Some atmosphere illustrations come from Wikimedia Commons (free Creative Commons / public domain licences). The other visuals, the logo and the graphic identity are the property of Lumina Studio.",
  'mn_maj'=>"Last updated: June 2026",
 ],
 'es' => [
  'mn_title'=>"AVISO LEGAL", 'mn_id_t'=>"Identificación de la empresa:", 'mn_id_edit'=>"El sitio %s está editado por:",
  'mn_l_raison'=>"Razón social:", 'mn_forme_v'=>"Proyecto pedagógico estudiantil (BUT MMI — IUT de Troyes)", 'mn_l_forme'=>"Forma jurídica:", 'mn_l_adr'=>"Dirección:", 'mn_l_email'=>"Correo:", 'mn_l_tel'=>"Teléfono:",
  'mn_cookies_t'=>"Cookies:", 'mn_cookies_p'=>"Este sitio puede usar cookies técnicas necesarias para su funcionamiento, así como cookies analíticas para medir la audiencia. Puedes configurar o rechazar las cookies en cualquier momento desde los ajustes de tu navegador.",
  'mn_pi_t'=>"Propiedad intelectual", 'mn_pi_p'=>"Todos los contenidos de este sitio (textos, imágenes, ilustraciones, logo, el nombre « Backrooms ») son propiedad exclusiva de Backrooms Escape Game y están protegidos por el derecho francés de propiedad intelectual. Queda prohibida toda reproducción no autorizada.",
  'mn_host_t'=>"Alojamiento:", 'mn_host_intro'=>"Este sitio está alojado por:", 'mn_host_v'=>"Servidor pedagógico del IUT de Troyes<br><strong>Dirección:</strong> 9 rue de Québec, 10000 Troyes<br><strong>Sitio:</strong> mmi25c02.mmi-troyes.fr",
  'mn_rgpd_t'=>"Datos personales — RGPD", 'mn_rgpd_intro'=>"De acuerdo con el RGPD y la ley de protección de datos, dispones de derechos sobre tus datos personales.",
  'mn_collect_l'=>"Datos recogidos:", 'mn_collect_p'=>"Al registrarte: apellido, nombre, correo electrónico, número de teléfono, fecha de nacimiento y datos de salud declarados voluntariamente.",
  'mn_final_l'=>"Finalidad de la recogida:", 'mn_final_p'=>"Estos datos solo sirven para gestionar tus reservas, garantizar tu seguridad durante la sesión y enviarte una confirmación.",
  'mn_duree_l'=>"Plazo de conservación:", 'mn_duree_p'=>"Tus datos se conservan un máximo de 3 años tras tu última reserva, y luego se eliminan.",
  'mn_vente_l'=>"Venta de datos:", 'mn_vente_p'=>"Tus datos nunca se venden, alquilan ni se transmiten a terceros con fines comerciales.",
  'mn_droits_l'=>"Tus derechos:", 'mn_droits_intro'=>"Según el RGPD, dispones de los siguientes derechos:",
  'mn_d1'=>"Derecho de acceso a tus datos", 'mn_d2'=>"Derecho de rectificación", 'mn_d3'=>"Derecho de supresión (« derecho al olvido »)", 'mn_d4'=>"Derecho de oposición al tratamiento", 'mn_d5'=>"Derecho a la portabilidad",
  'mn_exercer'=>"Para ejercer estos derechos: backroomsescapegame@gmail.com. También puedes acudir a la CNIL francesa:",
  'mn_resp_t'=>"Limitación de responsabilidad", 'mn_resp_p'=>"Backrooms Escape Game se esfuerza por mantener el sitio accesible y actualizado, pero no puede garantizar la ausencia de interrupciones o errores. No se podrá exigir nuestra responsabilidad por la indisponibilidad o los daños relacionados con el uso del sitio.",
  'mn_droit_t'=>"Derecho aplicable", 'mn_droit_p'=>"Este aviso legal se rige por el derecho francés. En caso de litigio, los tribunales franceses serán los únicos competentes.",
  'mn_credits_t'=>"Créditos", 'mn_credits_p'=>"Algunas ilustraciones de ambiente provienen de Wikimedia Commons (licencias libres Creative Commons / dominio público). Los demás visuales, el logo y la identidad gráfica son propiedad de Lumina Studio.",
  'mn_maj'=>"Última actualización: junio de 2026",
 ],
];
foreach ($__mn as $l => $arr) { $GLOBALS['TRAD'][$l] = array_merge($GLOBALS['TRAD'][$l], $arr); }

function lang_courante() { return $GLOBALS['LANG']; }
